//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceMeeter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Plugin : global::System.Configuration.ApplicationSettingsBase {
        
        private static Plugin defaultInstance = ((Plugin)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Plugin())));
        
        public static Plugin Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAABS2lUWHRYTUw" +
            "6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN" +
            "6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWR" +
            "vYmUgWE1QIENvcmUgNS42LWMxMzggNzkuMTU5ODI0LCAyMDE2LzA5LzE0LTAxOjA5OjAxICAgICAgICA" +
            "iPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW5" +
            "0YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp" +
            "4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+IEmuOgAABGNJREFUeJztmu1PW2UYh3+n7SllHRuFlkL" +
            "MWKgbERZmFTBREiOaKEs0jiUzQqzRwAKRzAX85P+gGGPMpiHROE1NpilGFhLnMjIzl4gSwoIl8lLpMrO" +
            "udC0vLfQN/NDIPLTlLsLpOSb39a3PaZ/z65We85znvivUVhs2wGRFo3QAtcOCCFgQAQsiYEEELIiABRG" +
            "wIAIWRMCCCFgQAQsiYEEELIiABRGwIAIWRKBTOgAAlJn34ZmnKnHUZgIATM8FMfKzF/cWIgonAwQlS65" +
            "6UYve7ka0nayBKEp/zPH4OpyDbnxwYRSxeFKhhAoKEkUNBvpPoOHR8m3fNzp+F2feGUY8vp6nZFIUuwf" +
            "1dT9BygGARns5+roa85AoM4oIslqMaG+tyfn97adqYbUYZUyUHUUENTdVQqfL/dQ6nQbNTZUyJsqOIoJ" +
            "sh4vz8pm9QBFBWq2Ql8/sBfygSMCCCFgQAQsiYEEELIiABRHILshcUghzSeH/Zt6tyCrobGc9RlztGHG" +
            "142xnvernzYRsgiqs+9HlsEMQAEEAuhx2VFj3q3bebMgmqMgoQvjX7kAQsLkjj0Z3XgBLJlNlK6vFmDZ" +
            "vkVHcVdbtkE1QaCmaNlZRlhLkub244/nm5kMAgHLLvrRji8uxHc+XK7IJ8gciiKzGJWOP1VkBANdvepF" +
            "I5F4hTCTWce2GFwDw+HFpkS2yGse9hfAu02ZHNkEbG8DYhE8y1vJsFfSiFj5/BM5Bd85zOQfd8PnDEEU" +
            "NXmiukhwbm/BhQ8aisayr2NWf5iWvS02FaDuVqiT2nx9NE5iJsQkf3j//CwCgrbU2bWnfeo69RlZBQ1d" +
            "msRKWXmZvd9SjrsaCWDyJzr5hOF1uJJPpl1syuY6vvv0dHb2pgn21zYRzW5b0lXAcl3+clfMryN/V6H7" +
            "dnvas4g9E0PPuFUxOLQBILd3NTZU49NABCALwp3cR12544fOn7i3VNhM+ea8FZWbpDfqjgd9w4YtxOeP" +
            "LL0gvanFp4GUcqTJJxteiSXz46Sicg+6sLR1R1KDtZA3OnWmAwSDtcU57gnil8zvZe2Z56YvZDhfj4sc" +
            "vovhAQdoxfyCC4atzGLvlw1++FRTotbCajThea8GJ52ywlKYv66GlKF57awgeb0ju6PlrHD5ytBQD/S0" +
            "wHTTsap7QUhQdvcOYmg7sUbLtydtufmo6AEfP5c0Hvv/C3HwIjp6hvMkBFGg9F+i1eOPVOjhOH8v51xR" +
            "cXMPFS5P4/OtbiMby26dXrDdfaNDhpeeP4OknD6HBXo4io15yfDkcw6/jd3H95m18/8MMVtcSSsRU9t8" +
            "d/1D9cAlcn7VKxlrfdOGP2fsKJXqAOiqKmfYKcu4fdoAqBMUzbFwzjSmBKgR57yxjxhPcfD3jCcJ7Z1n" +
            "BRA9QxT0IAEwHDXCcPgYA+PKbSdwPrSmcKIVqBKkVVVxiaoYFEbAgAhZEwIIIWBABCyJgQQQsiIAFEbA" +
            "gAhZEwIIIWBABCyJgQQQsiOBveBtImNHT9L4AAAAASUVORK5CYII=")]
        public string MicEnabled {
            get {
                return ((string)(this["MicEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAABS2lUWHRYTUw" +
            "6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN" +
            "6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWR" +
            "vYmUgWE1QIENvcmUgNS42LWMxMzggNzkuMTU5ODI0LCAyMDE2LzA5LzE0LTAxOjA5OjAxICAgICAgICA" +
            "iPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW5" +
            "0YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp" +
            "4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+IEmuOgAAA8dJREFUeJztml1z2kYUQI8AC8JXbIINZNK" +
            "mcRzHzkP6/9/70qfOuCkYgt00jUHCfNkYEEJYfWDcoBixkJGQMrPnDa20unPYvezeRXl3nLCRuBIJOoC" +
            "wIwUJkIIESEECpCABUpAAKUiAFCRAChIgBQmQggRIQQKkIAFSkAApSIAUJEAKEiAFCZCCBMSCDkBRFEq" +
            "FLMX9DKmUCjYMxyZaa0BTv8W2V5fMC/kMR4d5FBTO6zrt7tDb+IIs2qtqjF/flcikE0vbb+8Mzv5qYE5" +
            "nS9uL+xlOj4soyvyzOZ3x2++XnsYY2BRTFIX3K+QAZNMJ3h4dLG37Vg4APnzVgQl6XsiSXSEHwJhY1P9" +
            "uP7q+TI5tQ/Wi5XWYwQkqHmRXthsTiz/+/MLYmDqfc5FTrmlcd+48jzMwQemU6tr2PXL064EvcQYmKBp" +
            "d/uowyYGQrYPCJgdCJCiMciAkgsIqB0IgKMxyIOCtxsZyqhp6e3tyIMARtIkcCEYOBChoEzlAIHJgC1M" +
            "st5vk9LgAwPnHFp3efLe9iZxF8rkUJ28K2LZNpabT7Y98ifsB30fQydEBcTVGXI1x+DK39J515QCcvim" +
            "g7kSJqzFOXDayXuK7oGhs/gpjYvHhXHvUvo6c2ex+3lc0ws5O9GvfLqtxL/F9ipnmjNnM3jjnLDIcmQA" +
            "k4s5wp9byOpGX+C6o3R3S0G6+Ww6A1pon6L3dpOP6aDxddrun+C7o4tN69Rw3bgcGV9oNiqLwovTU0db" +
            "zOUFDAD/zG8m5MzirNLFtmxelpySffC2R2LaN3va+/vMtW11Ju62QP1/1yGYSpJMqkYjCYDhxFO1zu0l" +
            "ev8o7+tJaA0zT8j3mrQlyGzmVjzpa63bpM4qi8NPzXV7/kiey8KBl3XP5T8fPcP9nK4JWTatXP+eIq1G" +
            "6/RFjY4qCQjwe49leklIh65hWD1TqOpMtjB7YwrHPJjlnHaoXLa6aN950tga+jiC3nGNZM8eCbx0s655" +
            "KXed6C4l5Ed8Eucmp1DQ6vRGHL59RKmYduWUZtm2jXQ+4/NTZ2rRaxJcptkqOtlDsUneiHOQz5PaS5HM" +
            "pRx/t7pBef0SrfReImAc8Xwft59NryYH5UfGXZp+zcuNRP2flBv82+oHKAR8EvT3cX0vOj4KvK+lN5Cz" +
            "u1YxJsKNmEc8FlWs6Y2PKxLT4UG2uPXKq9Raj8ZThyKRce1wWCYpA//7yIxD4sU/YkYIESEECpCABUpA" +
            "AKUiAFCRAChIgBQmQggRIQQKkIAFSkAApSIAUJEAKEiAFCZCCBEhBAv4DqwLesGtEvG0AAAAASUVORK5" +
            "CYII=")]
        public string MicMute {
            get {
                return ((string)(this["MicMute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF+mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAxLTEzVDAwOjM2OjU5LTA4OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMS0xM1QwMDo0Nzo1NS0wODowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMS0xM1QwMDo0Nzo" +
            "1NS0wODowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpmZGY2MjAyNS05NWI2LTAyNDAtOGNiYi1mMTY3ZGVjMDhiM2IiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDpmMDYzZmFiZi1jNmFjLWNhNDctYjQ4Zi0zNDc2MTY2NmJiNGQiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDoyZjNiMjQwOC0xMWIxLTI2NGMtYTdmYi0yMDI" +
            "1ODMzZmQ3YWIiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjJmM2IyNDA4LTExYjEtMjY0Yy1hN2ZiLTI" +
            "wMjU4MzNmZDdhYiIgc3RFdnQ6d2hlbj0iMjAxOS0wMS0xM1QwMDozNjo1OS0wODowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpmZGY2MjAyNS05NWI2LTA" +
            "yNDAtOGNiYi1mMTY3ZGVjMDhiM2IiIHN0RXZ0OndoZW49IjIwMTktMDEtMTNUMDA6NDc6NTUtMDg6MDA" +
            "iIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3R" +
            "FdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHR" +
            "pb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz5jHZL4AAAKT0lEQVR" +
            "4nO2de5CWVR3HP6AChRKaY0qWNThK6DhtRl5qHGWCwEgpaPIy0ajhYBcYwsiabkY23ZQkp7IyL5NLpU7" +
            "QxcoCGzPdws0aEdBkukgamUFrTGHF9sfhHZZtn+/v2efseS7v+/vMMMzu77mc2ffznuc5t98Z1d/fj+M" +
            "UZXTVBXCajQvkROECOVG4QE4ULpAThQvkROECOVG4QE4ULpAThQvkROECOVG4QE4ULpAThQvkROECOVG" +
            "4QE4ULpAThQvkROECOVG4QE4ULpAThQvkROECOVG4QE4ULpAThQvkRHFgioueseQPKS6biuXAh4CDgV3" +
            "Ap4AVlZYognuuPabU+yURqEHcClww4OfxwMcINfOVlZSoYXTyI2ywPANZBIwtsSyNpVNrICUPwETgEGB" +
            "34nLMBE4AHgLWAY1LldKJAlnylMEE4C7glAG/ewyYBWytpEQF6bRHWB3kAbiF/eUBOBZ4GDiu/OIUp5M" +
            "E6qYe8rwQODsjNhZYTYOeDJ0i0K3A+VUXYi+TgINE/BVADw2RqBMEqkvN0+J3wDPGMScD3yqhLNG0u0D" +
            "d1KfmafFX4BM5jntjzuMqpZ0FqtNjazCfBD6T47j3A+ckLksUjXjOFqCq1tY8YBqhP+duQlM9i+XAScD" +
            "rjGveAHQB20aigCNNO9ZAVclzLXA78D7gCuBHe39WzALuM445HPhKdOkS0W4CVSXPucDiIX4/D/iece5" +
            "M4AnjmFnApQXKlZx2EqjKTsI3idjrga+K+C6CIP807rEKeMnwipWedhGo6qb68434JcB7Rfwh4O3GNcY" +
            "CXxhOocqgHQSqQ2vrhzmO+TShpsmimzDEoZiNru1Kp+kCVV3ztPgy8GiO49YCk0V8IfZgaq0muzVZoDp" +
            "1Ej4LnEboZVaMIcimrvNh4xpTgYvyFy0tTRWoDo+twfwNeDWw0zhuOvAeEe8G1hjXuDx3qRLTRIHqMiV" +
            "jKJ4E3pzjuKsJNUkWHzDOnwpcnLdQKUndE3048Bzgv5HX+TewA/ga9ZWnxU8IteNq47irCONdQ7EZWAk" +
            "sFecvI/w9KiWlQO8m9F0A7Bmha1ZVY84nfGATCIJcSXhkZfENYA5woThmLuHL0J0RXwm8g+y52VOBswh" +
            "DJpWR6gOZzj55WvcZiX9l0qo1VwC3AacSPrTFhJ7jLuP8dwHbjWPUu8zj2P0+C414clJ9KFlVc5PYARw" +
            "JfHCIWGvm4CHi/J3AO417dKFrqWsIj+8szgdeatwjKakEel6i65aN+iIcTxgIPUAccwdwp3GPZSK2Dbj" +
            "OOH+2EU9KE1thZWKtDTsRe6R8MXq5Theh+Z+FNaI/14gnxQXS5JlWehGwRMS3Al8yrqHGye4D7hHxGej" +
            "e7aS4QNlMJLws51nifBVwhIhfja6FZhNWa2Sxxrj/G4x4MlygbFpdHB8FfmAcO57Q7M7CqoXGAG8Vcev" +
            "+rzHiyXCB8nE2enoqhD6dV4q49a40XcS2AD8X8RnAocb1k+AC5ec84C/GMapf50HglyJ+FnC0iKuZjRM" +
            "I68lKxwXKzw700ALAW9C10FoROxDdJLfmTk8z4klwgYZHN2EoQ3GJiFl9Qqo530tYU5aFC9QQVJMdQuf" +
            "juIzYr/f+y+I0EdsFbBDx42WpEuECDZ9N6FHwF6Cnrqo+nePQIjwsYpMJsx9KxQUqhjVVQ/XL9BjnniR" +
            "i94rYOELPeKm4QMVYD/xRxE8VMdUSAzhKxP5snHuYER9xXKBi7EGvxJhCSOMyFFuB34tzVafgZqBPxEs" +
            "fmXeBivNdERuNroXuFzE1gNsHPCXix4pYElyg4mwx4keK2L9E7BTC0EbR+5aKC1Scx4CNIq46FNVa+AM" +
            "o/rkoaZPgAsWRZzHhUGwa0VLs42WJrpuJC+RE4QKlo12Td+2HC5QONeG+bXCB0rGj6gKUgQsUx8FVF6B" +
            "qXKDijKP4JK5UU1BL7yNygYrzYvTo9wMiljXdI5YnE103ExeoOIM3SxmMGvhUKzh6yO6pHkdFE8eycIG" +
            "Kox5De9DTNk4QsWdFbAy69lIJH5LgAhVjNHrS2Bayhysmo7Ot/kbEjiJMoM+iV8SS4AIVYybhHSgLVfu" +
            "oUXrQ7zFTjHNVIoYkuEDFWG7E1VQPNXEe9Pov9djcDfzCuPaI4wINn9mENVxZbEdPNlMT558Afivi6t1" +
            "pO/C0iCfBBRo+VoLLG8luRXUBLxfn9pL9GBqPboE9SnwqwWHjAg2PJeglyBByAmUxxzhXrdg4Gd3vpB5" +
            "9yXCB8jOFkDFM8U10B6IlkHr0nW6c6wLVnC9i/70+K2JnAK8S8Q3oGY5Kvj60uMlwgfJxF3Cmccwq9Id" +
            "4nnH+d0RsCrr19gAVjf67QNm0XmZvJqRPUWwHPiLik4FFxr1uFnErD6LqNkiKC5TN3wlruxbkOPZC9BY" +
            "Hy4BRIn4nIa1vFnON+//MiCfDBdK8NscxK4F1Im7VPqA34D2d8P6UxUYqGMJo4QJpVF5DgO+jN04B+Dy" +
            "69ulFt6DmG9e/0YgnJZVA6xNdt2x+LGKPYO8YNB/7/UXlVjyakPFe8W0jnpRUAt1E+HY2mUMJc3qGqmE" +
            "eIfQKPyPOn4idJLyHsPtQFsuAg0R8NfYeZUlJufRkDuHl70zsPbQs+giJA6xv40jSykC/krCF9wLguYT" +
            "9TW8hDF4qriPkClKoLPUvAi4zzq98O/DUa5fWYOc4Hg4bsZN2p2ATYS/4vFyG3gMDwo4+Ku/hUnSihR4" +
            "q3qkHmvcSfT12i6ZqZmDvsrMbPSh7InZCz8prH2ieQBAksqr2qpiEvbcFhC/Bn0Tc2ljXSrNXGk0UCMJ" +
            "jrG410WGEFHRqyikEwW4S8bdhdxyqMbdSaapAUK+aaAwhaZSVIexpdJknsf9GfUNxLxX3/QykyQJBfWq" +
            "iSwkZVi3ORed6XoVdg6kxt9JpukBQj5pIrdBosRTd47wImGdc4+vUrJO2HQSC6msia1Ph5cDnRLyLMN9" +
            "I8RRh87pa0S4CQbVN/BtErBs9WDoJ+GmOe1xBDTN+tJNAUJ1Eawmbyg3mduwOxduw33vuoCbN9sG0Yxa" +
            "t6/f+X3aP9eWEOdFzCX/Xddh7jN2PvdBwG3BxbOFS0Y4CQZBoFPZ7xUizAb0hykDuxpYHQg2mkotXSrs" +
            "9wgZS9Yu14uPYc6whvHyrpT6V084CQT2a+IM5AnucC8I7j3r5rgXtLhDUryY6hjAtRLEBWFhCWaLpBIG" +
            "gXjXRP4z4rwjzoK2+pVrQKQJBfWqizWTvndpLyHz2n/KKE0cnCQT1mU+0gP/PIbSesHiwMfJA+zbjFVX" +
            "1Ew2kj5DmZRoh58+D5OuNrh2dKBDYEu1ET5gfKYbTb1RLOu0RNhD1Yr0Ce9K8Q2cLBKEGuoB9c3QeB87" +
            "BntPs7GVUf7+1+NJxsun0GsiJxAVyonCBnChcICcKF8iJwgVyonCBnChcICcKF8iJwgVyonCBnChcICc" +
            "KF8iJwgVyonCBnChcICcKF8iJwgVyonCBnChcICcKF8iJwgVyonCBnChcICcKF8iJwgVyovgfTXWQa0J" +
            "v7VoAAAAASUVORK5CYII=")]
        public string SpeakerEnabled {
            get {
                return ((string)(this["SpeakerEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF+mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAxLTEzVDAwOjM3OjAzLTA4OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMS0xM1QwMDo0OToxNC0wODowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMS0xM1QwMDo0OTo" +
            "xNC0wODowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDo5N2Y4MDc2Zi00YTEwLTMyNDctYmE0ZC02NjYwMDQ2ZTNlZTQiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDoyYmE2MWQ0NS1mZTc2LWY1NDQtYTFiOS1jOTE1NmQzZjE5YjUiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDowMmFhZTkwNi01ZTBhLTliNDYtYWFhZi0xZjg" +
            "0OGQzY2Y1YmIiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjAyYWFlOTA2LTVlMGEtOWI0Ni1hYWFmLTF" +
            "mODQ4ZDNjZjViYiIgc3RFdnQ6d2hlbj0iMjAxOS0wMS0xM1QwMDozNzowMy0wODowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo5N2Y4MDc2Zi00YTEwLTM" +
            "yNDctYmE0ZC02NjYwMDQ2ZTNlZTQiIHN0RXZ0OndoZW49IjIwMTktMDEtMTNUMDA6NDk6MTQtMDg6MDA" +
            "iIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3R" +
            "FdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHR" +
            "pb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz55tAq/AAAKq0lEQVR" +
            "4nO2dT4zdVhWHf+f4/U+aZCYlaRWgYlFFQUVt0qaLBiGxAKEWECA2jQRiw5YVAiSQWLFoJFhX7EBqERs" +
            "EtGm7oIJNJyUEBSiUlqhCQCUUhaaTSTLz3vO997Dw82T+5D3b79pj+/l8kpXRzHu2M/O9n4+vj69JRKA" +
            "o88Jl74BSb1QgxQsVSPFCBVK8UIEUL1QgxQsVSPFCBVK8UIEUL1QgxQsVSPFCBVK8UIEUL1QgxQsVSPF" +
            "CBVK8UIEUL1QgxQsVSPFCBVK8UIEUL1QgxQsVSPFCBVK8UIEUL1QgxYtWESv93rlzGN5ax+2bt+DEgYh" +
            "yWW+r3c5lPTEcMMS6T4xGox8x84NEdGUcjr65fODe3+0fHICxYa7bSw+BmXD9xv8wHA8RcLDtpyKCVtA" +
            "CM2M4HqLb6QEAwnCMjeE6fvrss3u2p4UIVAeICCY0T1tjnmeOglhEHm0F7d+OwuHnzS3zQpnzBhAI1lo" +
            "wVfsg0UiBiAjW2qetMc/vTEcixnA0/K7AvQDkk5zzwsQgYgDVnQCjcQIREdwUeSIEzHwc4AMA1vZ6/3Z" +
            "TXXmAhhXRsTxmqjxKVhqTQLMOW3fBTRYlgUYkUPJhS5mXhU+gjMmjZGShE0iTp3gWVqBJ8pzVgrlYFlK" +
            "gSfKctcY8p/IUy8LVQHHylCnPPNut62y5C5VAW2qeWslTZxZGIB0kLIeFECg+VS9PHmpc8sTUXqAqnKp" +
            "Lgweta11EV2mQsK5FsC+1TaAqJE+8H808eEXUUqAqDRKWvf2yqZ1AxFyZQUKiqHhu5sErolYCxSPMpgL" +
            "yxPvT0NJnk0KK6CBgUNRnzIAcBiiAX3+NENE1Z+1XrbU/qYo8Ec02qBCBwnGI8Xh0xjr7HDM/ACCEZ4O" +
            "WiMAY06mCPIDWPjGFCLR67fox6+wrxLR/8q1c7sepyh+tKvtRBQqpgaw1nyGi/Yt6gqsC3aEQgYh5UMR" +
            "6q0Bl5SlptwoRSEQWdmx/hkDHAHwRwOk93BkAOA7I8bJOB2t1Gl820+Qh0LcAvAvgFyJyUUT+COD+Ivf" +
            "DiTtujHkjYH7LGPOWtfZNZn7Yub397KpAGRAROOd2Ll8G8MyOl54SkT8D+FBBu3JSRP7inH0oPnaJyAk" +
            "AF9qtzgMFbfOuqED+fG3K9z8gIn8A8OGct3cKwOsAdg1piEi/3+9/PeftzUQF8mdWyhwVkUsJr8nCI5j" +
            "IM+0FzrkP5rStVKhAGRGRbYtz7nJCK0deSXQSkTwzx9SI6E+e28mECpQSEUEQBGi12giC1ubSbnd+AGC" +
            "cULwenUg0bzqcBPB7AN2E1/3LOrt3kwOh5g1le4lzDq1WGwcOHIS1dvP7zHxlNBp98saN66855xDPNXQ" +
            "XjojIJSJ6HMC/M2z6JIALSE6eVWvtp0MzHmZYtzeaQClhZmxsrCMMQ7RarTutHCLo9wcrhw4tn4nP0mY" +
            "QJ1Hamig+bCUlz00iehyEf6Rcb26oQCkhIjjnsL5+G8D2WsiYEL3eYGVpaatEUwccj6QsrGN5phbME1a" +
            "J6FGArmT47+SGCpSBIAgwHG5gNBohCLbPWxhJ1F9ZWlp+IpLITlkLgEiiWUmUVp61ySHxSlltJSpQBuI" +
            "U2ti4jbsljDEGvV7/wvYkmsrRyYj1TomyJM9jAEpJnhgVKCNRCg0xHu9OISCWaLCytHT4CRGRBIl2nuJ" +
            "vDhIm7MaNO8lTLipQRu6k0Dqm1TmTw9mFpaXDH0+ZRL8G8BSAXyGdPKdRAXkAFWguohRan5pCwK6aKCm" +
            "JHgbwIpLHiSolD6ACzUWUQjK1FoqZnJ2lTaIk1qomD6ACzU1SLRQTSdRbSVlYT2O1ivIAKtDcbD0jo8m" +
            "E4NMWax0Gg30ry8v3nonfl4Gbk4I5YZCQAAhkj0/nixKoon2f+RKn0HC4DiAa+5m2jEYjdDrdlXvuOfg" +
            "RIqylvJf+n0R0DKmSRxA9IGFvf/V6LcyDqB9HsLa2CqYg1aefmUfMgU0pkAEwSvNCEQETo9ftp3l5bhQ" +
            "lUEPutos+9SKAFZPmDSeds68TcdKpesyDIvJudKkC/0l6MZWQQFoDeUHodnqbD0VJWE4RcRZ5YlL3E8k" +
            "C1UALj3UWnXYX/W4fdvZ1LyBFJ2ECeXc25oYKNCcigkFvACJO+tSn6CSMzswS7oYqqsfaCxVoDqy16HZ" +
            "66Hai9JlRdaTqJBRxb/Z6/bPMwdWCOxtzRwWaC8GgOwAxzZraLlUnIYBVEfeFXq/3s0OHlr+UYrAx7ie" +
            "qRBKpQBmxzqLT6aHb7cHZqbVPtk5C0BVrbXztrIjOxsJQgbIiwKA7ABNPS5+MnYTRIKHI1laQXDsbC0U" +
            "FykCUPl10u71tjfVbmKOTMCK6R1Dy7mwsHBUoCyJ30mf3mVdunYTzdjaWMXOICpQS6yx63T76vX0QF10" +
            "2YA7A0SSbuXcSenY27hkqUEoIhE67B+sMQhvCWANjQlhn7yPQqyigk3COzsZX0q47L1SglDAz1oe38N7" +
            "qNazevI7Vm9fx3o1ruL1x6xvMfCjh7XN3EmbsbDzhnPtK1m34oAJlIBotlp3LqYS3eXcSZulsZOY9Lah" +
            "VoAwwM4Ig2LYw89UZb8mtk3BrZ2PUe7RboonQ7/huKwsqUGoIxhqMwxHCcDxZRrDW/HjKG9bSdRKmJy6" +
            "sDx5cPhPfVh0z+fqvztmf57W9NKhAKZn0jsEYExXQ1iA0Bta514joSQDvx68Vkcsi8jEU0MNsTIh+v7/" +
            "S7XYfcs5d2vKjV/cd2P+pw0eP5L3JmRTSUCYiXNnZTOdERNBqteDEwjm3OV/i5J+Xieg+InrEGLMh4t7" +
            "gGY32vkS1GP5GhNNEdL911rWD9tV2u4NOL+nqSb4UIlC70xmbMKzulLgeBNyCc+O7/WgM4KKIbHYnF8v" +
            "m4eu/mw9dcA7OJPYm5Uohh7Ag4MuL2NQaTzLFPPU6GBbwMzOTQgQaj8YXOeDvFLHuKhCw3osQU8hvYvI" +
            "JfUZEfklEjxGRgd/DVt4H8FER+SFKvpMkTiHreNoF1UZR6B9DIG8T6O2cVvcbAO8guoe8dAJuqUAo+DS" +
            "+gELyPIDP5b3SrKSphZpCHceBXkQFJAKAINBaqI4CARWQSEQQcBDdkdrgFKqrQEAFJAIwc2aOJlBngYB" +
            "Ios+WvRNNpu4CARUprJvKIggEVCCJmloHLYpAQJREejjbYxZJICCS6KmyNh41dAFlPX6yDBZNIAB4CSX" +
            "VRCIC5uhujWzTrMjmszfqxiIKBJRYE9Hkdh/C7meLTV+AMAxrGVyLKhBQWk0kiGcuS0v8JKCkGV+ryCI" +
            "LBADniajyhXXSMziqzKILBEQSlVZYpyV+ElDdUqgJAgHAS1VPorSz31eNpggE1CCJ0s5+XyWaJBCQPok" +
            "YJfxu6lgLNU0gIN1gY3wqtefULYWaKBAQDTbOSqI3RORm+nGc/BYgmsQzSqHq0+SWuvMAnkQk006+X+a" +
            "ocBAEMMbAWoudtzBXjSYLBAAvA3ISwDmATgD4O4BvE9HlMneqTpc0qMp2K9WnqTWQkhMqkOKFCqR4oQI" +
            "pXqhAihcqkOKFCqR4oQIpXqhAihcqkOKFCqR4oQIpXqhAihcqkOKFCqR4oQIpXqhAihcqkOKFCqR4oQI" +
            "pXqhAihcqkOKFCqR4oQIpXqhAihcqkOLF/wF33aLSldTI6wAAAABJRU5ErkJggg==")]
        public string SpeakerDisabled {
            get {
                return ((string)(this["SpeakerDisabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAABGdBTUEAALG" +
            "PC/xhBQAACyZJREFUeAHtnXuMVcUdx3+77PsBLhgWVBYQebSigM80is8mxjStxme1xT/a/mPEGqDUxtd" +
            "faoyNRlCCGv/QaKRBjY+krbba+qyaCKy4GKjgyj6EBXYF9t5d9sGu8108Zr1753fv3XHumbnzm4Rcds6" +
            "Zub/fdz73nJkzv5lTNNC4bJgkiQLjVKB4nOWkmCgwooAAJCAYKSAAGcknhQUgYcBIAQHISD4pLAAJA0Y" +
            "KCEBG8klhAUgYMFJAADKSTwoLQMKAkQICkJF8UlgAEgaMFBCAjOSTwgKQMGCkgABkJJ8UFoCEASMFBCA" +
            "j+aSwACQMGCkgABnJJ4UFIGHASAEByEg+KSwACQNGCghARvJJYQFIGDBSQAAykk8KC0DCgJECApCRfFJ" +
            "YABIGjBQQgIzkk8ICkDBgpIAAZCSfFBaAhAEjBQQgI/mksAAkDBgpIAAZySeFBSBhwEgBAchIPiksAAk" +
            "DRgqUGJUuwMKNX/TQV1/3pfVs1gnltHhuVdpjoWYKQCkt//qHh+iVd75JyT3255UX1glAKcrILSxFEPk" +
            "zNwUEoNz0krNTFBCAUgSRP3NTQADKTS85O0UBAShFEPkzNwUKCqA9BwbomX8cyE0BOdtIgYIZxm/7spf" +
            "+tLaVvukepM6Dg7TyxmlGwtgq/N9Nh6luYknBPA4oCIDe3dJNdz/ZTn39QyPtvvGtrpFP1yD6zyeHR+w" +
            "smUD04PIGOvfUaluc5q1e729hHzcl6I71bd/DEykHiB5+fm/0Z+yfETxHjw4rW4dp1ZoWAvi+J68B+mx" +
            "XL92+ro0GVaOkS65ANBqeyE7YfNcTbdSkbr0+J28Bat/fTysfaaEj3922dI3wspqW2L77iO6w9fx08ER" +
            "f2j8wTKtVv+3rA/1RlnefXgI0ODhMdz/RTt09R1nBp9aV0uO3z6IFMyvY82wdRJ/skb91EG5buoROPyA" +
            "aUD75mLwEaN1L++jzZv7Sf/KJ5fT0PbPp1JMrY2uX8rJiWrtqJk1Woy4u7Wrvo/UvdXCnOHvMO4A2b0/" +
            "Shn91soLOml5G61Znbji2kh/pYLa2bPh3F235f8+P9K35q8YrgIaGhunhDfzIqn5yqYJnFtXV8r/6/El" +
            "MNFvFEQFozqZhdQd74Jk97O0unzZn+11eAYQO8c629MFecLhkQhHdf/NJNGWSO/BEDQGI1qxsoNKSoih" +
            "rzOfuvX302nsHx+S7nOENQBhtPfnKflbLFTfUx9rnYY1TB+c1VNDya6eypz312v6MI0u2gjwf9Aagv39" +
            "wkA4l9KMuhJpeffHkPMuX+9dd//MpdPZP9U+gOw8NqohIf65C3gC08c1j0xPpmmyCunWtXubm3Fc6e1f" +
            "8ehoVF+tvZS+/nT6kNl1dced5AdDH25K0e6/+YdsVS4+jOSfG86xnPA2IRwxXXHCctij6QpvUaNOH5AV" +
            "Ab3ykv6QXqR/yjZdN8UHrH9h40+XHE2zXpVff9eMq5DxAGN7+77OETme6cEktnTS1THvc1QPTjy+l8xf" +
            "Vas37qClJeGzhenIeoK07e+hgt77z/Mulda5rrLXvqov0th9OHqVtzfHN4WmNTjngPEDo/+hSZXkxnf0" +
            "T/YhGV86VfIzGqir0TfDhVvfDPfTWO6Lyjt36Oa+fnVZDZaVMR8IRH3Rm4MHnOcyQ/vOv5Aqk0y7r/J1" +
            "tehEXFcAy47OYK2izZol11uLl4USnr0AJFa7R0TWolWHuDH+G7jonTmF86OgaoGSvvv+nqzOf+U4D1K5" +
            "WWXBpHiM+V86lY3PUMyEute7TP//iyuXrmNMAJZmAsQoVa1NT5bT5WbVhbdUEqq5UUfaalOw9tlBAczj" +
            "2bKdbIMGIV1vttOk5NWxNpd4X3MZdTnrLHbA6wdz/8cstlFTNAcT8iFzw373AmVGq4Cm0LhWRneH7X26" +
            "aTviXz2TLl3z44PQViO0bHHH70p5L4yUZXzgNcvkOW+c6DVBlmf4qw93ebIllq17Ol6pyvQa27MmlXqc" +
            "BmsTENSd6hgjzRb4n+ABfdGlijdt9PacBaqjnZ9m5GCFdg7iWn8mHhnr+OVHc/jgNECYauQD5pl3+LYN" +
            "JbXDOB/jOTbam1hXH304DBEGwmkGX3mt0f7ZaZ3uUz/nA+R6Vj/vTeYCWzNeHazR+0csG2sctbqbvxyI" +
            "B+KBLS+a7vye18wCduUAvIiL23v/U36sQbOeiDs9coP/x6KDLd77zAC2cXcn2A97xeI8dznb0feC768l" +
            "5gErUSs6LztDHDr//aYJ8iJtJBQE2w3Zdgs/w3fXkPEAQ8Bfn6ZfA4Baw7sV9rus8xj7YzN2+OJ/HVBZ" +
            "jhhcAnaE60tOmlGplQl8CL0nxJcFWru8GX+GzD8kLgLB+6jcZ1n49ttGf/XUy2QpfuTVjLoHlBUAQ7Fd" +
            "q9Sm3URP2Gsy0b5ALwsNGbl9E+AhffUneAITdvpZdzq9AffSFfcQtA4q7UWAbbOQSfISvviR/LFWKXnf" +
            "pZMK6cl1Cp/SO9a1qHb1+DyFdWdv5sAm2cR1n+AYffUpeATSyC8dv+WAvxBBjx3qXZuphC2zKFN+8Wvk" +
            "GH31KXgEEYZfMq6JrLuF/pa0d/fSH+5qduBLhyvN7ZQts4tK16soD33xL3gEEgW+7vp7mq92+uNSiGux" +
            "39zbH2idCnwc2ZIIHvvzxunrOHWePeQkQ9hm8T+2FmCmwHreMFWoz8jhGZ/hOfHem2xZ8gC/c3onO0qM" +
            "MKxpoXMaErrtsOhF27rj1oZYx78lIZ/VCtV/0cvUrt/3WZTwkxHMebqge2YfR1qOrGuj0U/y7dUU+eA0" +
            "QnPhga4L+/Fhr1tvjYk+eW66ZysYZReLk8om5LUxPcE+YR9eHzvKDy2fQeafXjM727v/eAwTFAVG6N/b" +
            "oWgP7E56/qGZkcyoANWmccceI5wEwmFXHxCg3RB9tC6482I7Yd3jgU0EABEdwO1u1pjXj+zNw7ugEmBb" +
            "PraSli2tp4ZwqmjmtjCZWpw9kx3AcMcwIQ0UkIYLBsoUm+k70eR66bYbXt63IF3wWDEBwpk1tRHCnenf" +
            "Yjhb9ljA4L1PCmvsatV69uuIYSFi3haU33OqJTHXiOEZb6DD7uCWfzr+CAghO4q03a1Un9oXv3lqoczz" +
            "f+XjOg6G6r6MtnV4FB1DkKF5c8tfn9tCX6k04cSZMT+AJs48PCbPRrWABgvN4TxfeWvjsPzup67B+o6p" +
            "shMr1HMyqY2IUc1u+TU/k4mtBAxQJgRe/vapeYvL8G520t5PftCoqM95PBINh32psfu7TrPp4/Q0CoEg" +
            "c7PaxeUeS8N6Ntzd3U88R/ZLiqEw2nwiARwwzwlARSehLMFg2vmU6JyiARouB12Y2qbcebtreQ1sUVHg" +
            "QiBedZJOwYhSL/rBmDcuOsHrChwD4bHzL9ZxgAUonFK5ImIQ9pN5j2tM39P0VCleYKrUnNTZ7wHp915c" +
            "bp/PNVp7TG0zZclpXL8CI6wW9Optcz/dyNt51UUOyTwAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgA" +
            "KqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+Co" +
            "AWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCo" +
            "FoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24K" +
            "vApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+Potxx8cBjcuvCkAAAAASUVORK5" +
            "CYII=")]
        public string OnOffEnabled {
            get {
                return ((string)(this["OnOffEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAABGdBTUEAALG" +
            "PC/xhBQAAC1JJREFUeAHtnftvVMcVx49522AbiAA7fpUQMHYwpooN5hWVxpaCE4UkVKU/NCotjwbSpk1" +
            "bG2Obgh9Sk6qtgEhxCPAHpDVKIMRuw69xYhrJDwwBQiC2CQQEwYDBtnj2HqONtmZmdpbxrmeW70ho1+f" +
            "M7D3ns19m773zuFEpqWl3CQUEHpDAsAdsh2Yg0E8AAoIQjAhAQEb40BgCggaMCEBARvjQGAKCBowIQEB" +
            "G+NAYAoIGjAhAQEb40BgCggaMCEBARvjQGAKCBowIQEBG+NAYAoIGjAhAQEb40BgCggaMCEBARvjQGAK" +
            "CBowIQEBG+NAYAoIGjAhAQEb40BgCggaMCEBARvjQGAKCBowIQEBG+NAYAoIGjAhAQEb40BgCggaMCEB" +
            "ARvjQGAKCBowIQEBG+NAYAoIGjAhAQEb40BgCggaMCEBARvjQGAKCBowIQEBG+NAYAoIGjAiMMGodgY2" +
            "zZs2i1LRUYWadHZ3Udviw0PewGiGgAd/80/lP07OFhQOs9/78qK4OAhpABj9hA4Dgz+AIQEDB8ULtAQQ" +
            "goAFA8GdwBCCg4Hih9gACENAAIPgzOAIRJaCEhAT62YoVwRFAbSMCEXMZn56eTtVVlTR+/HiaOHEivV1" +
            "TYwQmVI0XL15EXZe66PCRI6E6RFg/NyJ6oAXz59M//v63fvEwvRdffIHWr1sXVpA6B3vqqcVUVlpKb7z" +
            "xF8rJydFpYn0d5wWU8+STVF5eRqNGjfo/2LaJiMVTunEjDR8+nEaPHk2VFVuIhe96cVpAmZmZtHnzn2n" +
            "kyJHC78EWEfmLxxcox1xWVkoZGRk+k5OvzgooMTGBqquraMyYMUrwzz33LM2YMV1ZJ5ROkXh8x+Nek3u" +
            "ihIQpPpNzr04KaMSIEVReVkax48YpgV+8eJFe/8Mf6csvTyjrhcrJAln3yiv9P1uyY/BJf2VFhbQXlbW" +
            "zxe6kgFavXuX1KjOUDNs7Omj9q7+h48ePK+uF0nnjxg3aULKRurq6lIeZOnUq/eqXK5V1bHU6J6Ds7Gx" +
            "a/tJLSp6dnZ1UVFQc8ItTfsggOftjKQ4cy/LlyykrK2uQjhq+j3FKQMOGDaNX16svzy9cuEBFxRvo8uX" +
            "L4aMY4Egd3jyiIk9EqpiioqLo9d//TvlzF+AwQ+J2SkA8T4e7e1m5efMmVVRW0aVLl2RVhszOIirZWEo" +
            "co6ykpKTQ0meekbmttDsjIL7aWrnyF0qINTXvDOk5jzI4z3ny5EnauWuXstrLL/884JWl8gPC7HRGQAX" +
            "5+RQXFyfFw1NNP9y/X+q3xfH++x9QU3OzNBwehilculTqt83hjID4pqCs3L59m7Zvf0vmts5e83YN3bl" +
            "zRxoX37typTghIB434vMDWamrr6f29naZ2zo732LgmGWFc50zJ1vmtsruhICWLPmRFNrdu3eptnaP1G+" +
            "r4733/kkcu6y4cjJtvYD48nbe3LkyztTQ0EBnz56V+m11nDt3jj5rbJSGl5ubS3zbwvZifYSZmRkUHx8" +
            "v5fifjz+W+mx37N//kTTE2NhYmjlzptRvi8N6AeXm5EpZ9fb2UlOT/IpG2tASR0tLC/X09Eijmev1QrY" +
            "X6wU0bdo0KcP/fv458XiTq4VvKjY1NUnDT09Xj/dJG4bRYb2AHntMfuf5iyNfhBFVaA7V7PVCspKWliZ" +
            "zWWO3WkBjx46lyZMnS2F95d3Zdb18fepraQqTJk2imJgYqd8Gh9UCSkxMVDI6deqU0u+Cs72jXRlmUtK" +
            "jSv9QO60WEPdAstLX10fXrl2TuZ2xd3dfU55IqxjYkKTdAlJ039evX7eB36DEoMolJkb+n2hQDm74IXY" +
            "LSNEDdUdA7+P77q4rLuXHKRj42g/lq9ULC/kutLQohgGkbTQcW7duI/4X1hKiXMKRg9U9UI93o1BWoqO" +
            "jZS7n7KpcVAxsSNRqAfUpBGT7yWUwX64ql17Fz1swxwhVXasFdLX7qjTvcd6SHh4vcr1wDpyLrKgYyNq" +
            "E0261gL755oyShWqOkLKhRc5AOZw5Y/dMA6sFxAON330nnyCf4cBodSCtqnLg3FWDrYE+Oxx+qwXEAHh" +
            "dlawsWOD+5gSqHFS5y5iE2269gA61HZIymeXt6ayaaC9taImDY+ccZKX1UKvMZY3degG1NMtHq3nGXt6" +
            "8edbADDYQjl0167C1BQIKlul99Y95a9tV5wELFy28r40rBlXsnDPnbnuxvge6desWfeLNe5YV/l+cJnk" +
            "0gayNDXaOWdV7cs6cu+3FegExwAMHDkg58k/AqlWrpH5bHRyz6udLlbNNOTkhoNbWQ3T+/Hkpt/l5ecQ" +
            "PSXGlcKwcs6xwrpyzC8UJAfH6qX/V1ip5rlmzWum3yRkoVs5VtWbMplycEBADq6//t3K/H95rMNC+QTa" +
            "A5xhV+yLyZlScqyvFGQHx6gtezakqa9eusXr7XF6izTGqCufo0koTZwTE0D/Yu5d4Xbms8ElpubfzaaD" +
            "xJVn7UNo5Jo5NdeLMuXGOLhWnBKSzCwdPjaiqrLBqpJ5H3Dkm1bQNFg3vMMI5ulScEhCDbWtro337PlQ" +
            "yTkpKou3btlrRE3HP89b2bcQxqcrevfv6c1PVsdHnnIAY4js7dtCJE18peSYnJ/d/cUP5SAE+to54OJc" +
            "d776rzMdW5/D4+PFbbA1OFhdvztTs7fKVX5BPowc84sC/De/T/OMlS6i3p5eOHj3q7wr5e77aKi76U/9" +
            "jDVQH48UBJSUldOXKFVU1a31RKalp8k1qrA37XmBPPJFJf33zzfuekyEKmwW0c+eukD80l28S8n0e1aW" +
            "6Lz6+2iresIGOOLxE22kB8ReRlzePtmzerL09Lu/Js3v3buJdUwez8NgWD0+o7jD7H49Plrd4O9Q3Nh7" +
            "0Nzv33nkBMXEW0abycq2eiOvzT2DjwYPU8ElD/+vVq/K511xfVng+Dw+I8qh6oKkZ/p/BPU9VdbXz4uG" +
            "cIkJAnAj/nFVVVQV8fgbX9S8spsPeDq+ffvoZHT12jE6fPk3d3d3+Vb5/z5fjfFXF01B5JiFPBlPd1/m" +
            "+od8bPufZtGmT0z9bfulEjoA4qUe9zRjKvZ5o+vTH/XMM+j2vueflxryBFRdet8X3cFSrJ3QOwldb1V7" +
            "Pc/bbb3WqO1EnYnogH21+Dtev166lZcue95mseOX7PHyprtqp3opAgwwi4gTky58fXPLaa7+lHwzxJk0" +
            "8PMF3mPkGaCSWiBUQf1n8eMkXli2jFSt+ShMmTAjr98ej6jwwymNbrg1PBAMqogXkA8E3FAsLl9JPvEc" +
            "qTZkyxWcOyStPBqvds4fq6uqdGlV/UBgPhYB8cHi3j+zs2VRQUECLFi4ctO3jeAI8z2Hmaag8k9CVyWA" +
            "+LiavD5WA/EHxYzNnes+an/PDOTQ7azalpqbSI49M9K8ifc8rRnnRH69Z42VHvHrChQnw0oQMHA+tgET" +
            "MeEPL5OQkiouNo+iYaIoec28Lmd6+3v7xNN7ogNfrq5YZiT43km0QUCR/u2HIzcnpHGHggkNoEoCANEG" +
            "hmpgABCTmAqsmAQhIExSqiQlAQGIusGoSgIA0QaGamAAEJOYCqyYBCEgTFKqJCUBAYi6wahKAgDRBoZq" +
            "YAAQk5gKrJgEISBMUqokJQEBiLrBqEoCANEGhmpgABCTmAqsmAQhIExSqiQlAQGIusGoSgIA0QaGamAA" +
            "EJOYCqyYBCEgTFKqJCUBAYi6wahKAgDRBoZqYAAQk5gKrJgEISBMUqokJQEBiLrBqEoCANEGhmpgABCT" +
            "mAqsmAQhIExSqiQlAQGIusGoSgIA0QaGamAAEJOYCqyYBCEgTFKqJCUBAYi6wahKAgDRBoZqYAAQk5gK" +
            "rJgEISBMUqokJQEBiLrBqEoCANEGhmpjA/wA6Xsalee3D6QAAAABJRU5ErkJggg==")]
        public string OnOffDisabled {
            get {
                return ((string)(this["OnOffDisabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF+mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAxLTEzVDAxOjE4OjEwLTA4OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMS0xM1QwMToxOTozMy0wODowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMS0xM1QwMToxOTo" +
            "zMy0wODowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDo1Yjc3Mzk4Yy0xZjhhLTVjNDItOGMyNi04M2Y4NGYxYWQyM2MiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDo0NzkwZmExNS1hY2YzLTUwNGItOTMyNC00ZmUwNTZkZDFjZWIiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo3NTc5MWVhNC1lYjFjLThmNDItOTg4YS0xMjR" +
            "kMDBkNzJiM2QiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjc1NzkxZWE0LWViMWMtOGY0Mi05ODhhLTE" +
            "yNGQwMGQ3MmIzZCIgc3RFdnQ6d2hlbj0iMjAxOS0wMS0xM1QwMToxODoxMC0wODowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo1Yjc3Mzk4Yy0xZjhhLTV" +
            "jNDItOGMyNi04M2Y4NGYxYWQyM2MiIHN0RXZ0OndoZW49IjIwMTktMDEtMTNUMDE6MTk6MzMtMDg6MDA" +
            "iIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3R" +
            "FdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHR" +
            "pb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4xbACAAAADeElEQVR" +
            "4nO3d3XGcQBAA4cHlQJyIUlIwSsmJKBP8RJmi9AfNsjO7/b2LA7ZvQHcn3bKua0hX/eq9A6rNgIQYkBA" +
            "DEmJAQgxIiAEJMSAhBiTEgIQYkJDfvR54WZam2395fT/7I2ffFDx1AH/f/pzc/Dm93tPsFlAS5Kzvf7b" +
            "tsyGxmS9hdz5lp/1Iw4wTqNVib9udahrNNoGemBRTTaOZAnpyYaeJaJaAeizoFBHNEpAamSGgnpNg+Ck" +
            "0ekAZFjDDPjQzekBqzICEjBxQpktHpn251cgB6QEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBiQEAM" +
            "SYkBCDEiIAQkxICEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBi" +
            "QEAMSYkBCDEiIAQkxICHdvvLy5fX9zH9vL/81khe+RTri3H+473KOnEBCDEiIAQkxICEGJGTkgDL95pZ" +
            "pX25VJaBhv7DtCyWOuUpAlQ07fSL6BvTEiR168Xa6HWelCXR1pPeM6Opjl7h8RdQKSAlVC6jSFHpq+nS" +
            "9TPcO6MmDH/Wxuuod0BXk/iD7jXuZe59NhoCefrYujR6z1Xa/e8yuMgR0xR3P1DtP/h3bKjd9Ijp+oOx" +
            "gifMncA2+cPuf73nzeiWe7tMnIk9AGaRYkGoyXcKuLGDJsX9QdvpE5AroqsoRVd73iMgX0PAv/e9UelH" +
            "0U9kCIipFVGlfv5QxIPpCXObFofuXavpE5Awogp+ojBHRfUoXT0TegCLuiShDSHfsR8p4InIHFFH/Fd5" +
            "sr5jfbpYXEvcL2XpBMky9x2SfQBH3L3irS1uL7aaePhF1JtCV98q+c9ze2cVqPWnSxxNRJ6CI/ye01cJ" +
            "lufSUCGdT4RJ2VOoEn1Tu2CoGFFHwRP9AyWOqGlBE0RP+ibLHUuke6COt74taKxvOpnpAm2ohlQ9nU/k" +
            "S9pEKC1NhH39slAm0l3UaDRXOZsSANuQD8y32YUgjB7T3ZEzDR7M3S0B7xwUe9qMWT5gxoKOr90xTh7M" +
            "Z7bcwPcyAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhCzrmu2vX1SJE0i" +
            "IAQkxICEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBiQEAMSYkBCDEjIP0rEWVN4W4JCAAAAAElFTkS" +
            "uQmCC")]
        public string Mic2Enabled {
            get {
                return ((string)(this["Mic2Enabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAQAAABNTyozAAAAIGNIUk0AAHo" +
            "mAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwA" +
            "ACxMBAJqcGAAABuBJREFUeNrt3WtsFEUAwPF/W0RBwWqE4AtEilAQidBisQ2JhLYU/IAxIkRiwIAoFj6" +
            "pIRg/EE0Mxg8SQEWs0QQRJFGDiraHL1rQ9lpUQItiY6xvxSBCIq+2fgCCcrOzj5ndndubuW+zs3tzv9v" +
            "d2XnsTN5D2CAL+ZbAAlkgC2SBLJAFskAWyAYLZIH0h15G5KKIasopZjD9gMN00k4T9XTEn7W8mCurBcx" +
            "iMTc5bP2E1WyiK3cvsRraWe/IAxN5hS+pyk2gvrzIVoa7phtBPevok2tAA2linufU82lkQC4BDaSRG33" +
            "tMT4uIv9AhTRQonhxvcd1vvcawVYuMB+okBSVpBiv8J2rfJ49Z0IJT5sOVEiKEqCQbYGJargncG4XMsV" +
            "koDM8KBAVsFIpv6uivmvmB+IJTjTLQ8EuCyOZaSbQuTxBiWqVc1xrIpCIJwhREWXKOS5nqHlAmx0Ldn9" +
            "E1VryXG0e0DL+kpxd3okqtOS5wjygNFVaiIq15LnYPCBdRFdryfNgM4t5HUT9tOS5v6kPiupE52nJc29" +
            "zqxqqROvIuuD3wV2NaGH2Efmv2agQ9WQfUZCqX5oqDuUKUbC6cZpKJaLnkw6kSnRf9hAFb13JESKV5qe" +
            "cIFJrn8sBItUGTFWitUkHUiW633QiHU3giSbS00eQYCJdnShuT9cpF6Lnkg4ELVKiS1yIFplKpLMbLpF" +
            "EevspE0ikuyM3cUT6e7pViZ5NOpAq0QNmEYUzViJBRGENJkkMUXijbVqoViJ6JulA0KxEVGsGUbjjtRJ" +
            "AFPaAtqwnCn/EX5YTRTEksjmbb9fRjBlVISJeoqgG1WYtUXSjjpuplrz5ZSxRlMOymzkq2epOtCbpQG7" +
            "Bjag2DiKzXuo1kMi0t56NI1IDOsbJjE+pJP1xLURPSLaW0pPx6YoPqJuCjI9sDOphLWfRMsk20butR+M" +
            "DEv1g2VDfH3xcaOMCXqJB/5ZQgP4UxF0mSd/u44duC0R0uSDuj/iAfhLEjZSkb/J1LgQhEr0J9GN8QN8" +
            "J4kZJ0qfoDplotMdcRgT0lSBujCT9z3zk847il2icx1xGBPSFIO4q6Svfq33fdP0QDRPegz6PDygtvGR" +
            "kc228ye4QiUSv2p2gLc5iXnQO1Uj26GFJgKLbK9EMQVwr/8RZ1UgJ/8crJHt87Psy80o0iMmC2IZ462J" +
            "vC+IKmCvd50GaQyGaR4Egdku8QDv4VRB7r/TNsGPc6uOR0TvRpYK4DnbFC9TNBkHsEJfpJw4wibR2ooc" +
            "Fr8msj7+54wVh7KMuM7UcYFKAYeRyosw3ibqoix+onQ8EsVey1GW/oyykiq9DJXrLc/U4RCB4yqFRYoy" +
            "HMnA0c3zesv0QPan+4/TMgtcqbL9p42ZPTWSnpgmsoJgh9COfQ3TSznQuckx/kCmSm28ea1kAvK9jMh0" +
            "9QFXUO9yfFvjPET0AVPCuIlFZgMeJzGeWch1AHZRRJKw6HghQWp0KnTQy0/EV8D7MJMUvkuezfQ5/Wix" +
            "nEAxnD+cL4ru4i02Bj6pyFmkKuno19vOY+AzlFe4IfNQmpnJEa3tRbECwwuFiKmADixSe1KdK2pQjINI" +
            "HdJLZ/C3c0os1rAk8re4OauIk0tlx2MHc0yVQZlhEY4C5Ew0g0tuz+gbLHbeV8RlLhPVtoy803V3Py3n" +
            "JcVtfVrKbaYGOuzMuIv198/N5XbJ1FO+wnRkBvvdTVim2F8X6HPTf0JuN3OZ6v6rjNc8zjl/LHOZxjUu" +
            "qUJ6LwpmRvBd13O0h3S7qaWSHQ+kH/ZnAZKYx1uP3hkAU3pTtj/OIx5TdfM+37Od3jnCYk/ShkEEMpZi" +
            "h5Pn8Vu1EYc5pfyd1XEjUQTNRmAOoNlHiuxdMPWi+XYc7wmwfpayIfFUDrURhD8E7zlIm0BrKsU9EQRT" +
            "FGMVdTGCu2iCUjLCX6ZRL5lLTRhTNIM4eXqaIxXRqOdoeZjOWrS7TzWkiim6U6zFWM4zZbFc4RhdbqOI" +
            "GNp4eNBEBURxL1wxnDrcLhzrJzsFmNvOqoJG1lAYKwyv041vbZxiV3MJElwlwe/iGnXxIA785pgmVKC/" +
            "2lXoHcL2w6xGgnL2O1ZCIiPKMWMrYqZnNe0WjlBQXh0GUlAXY5FM8Kdyuk7NCXUhESVrCLxSiZK1xGAJ" +
            "R0haB1E6UvFUyNRMlcRnRtMvMM76IkrnOaos+oqQuRKuNKLkr9WoiSvJSxm5EK3IdSE7U5m0pt6Qvhu0" +
            "0UVgblRy0QCCeVqWVKd54cmM59XOJ0lRKGmpzEOj/RL54cgXoLFGLtCKSw0CniBqkBb8wmNHkanDItwQ" +
            "WyAJZIAtkgSyQBbJANlggC2SBLJAFskAWyALZcDb8C7SDM8ogjdusAAAAAElFTkSuQmCC")]
        public string Mic2Mute {
            get {
                return ((string)(this["Mic2Mute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF+mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8" +
            "vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS9" +
            "4YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2V" +
            "sZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3A" +
            "vMS4wLyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAxLTEzVDAxOjM2OjI3LTA4OjAwIiB4bXA6TWV0YWRhdGFEYXRlPSI" +
            "yMDE5LTAxLTEzVDAxOjM2OjI3LTA4OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjAxOS0wMS0xM1QwMTozNjo" +
            "yNy0wODowMCIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpiNzNiNjlkMy01NmZhLTE4NGMtOWRmNC1" +
            "mZjcyMDdlNTZlNWYiIHhtcE1NOkRvY3VtZW50SUQ9ImFkb2JlOmRvY2lkOnBob3Rvc2hvcDo5ZjBjNjJ" +
            "hNy05OTAwLTk4NDAtOGVkMy1kZDI1NDQxZDRiNTQiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1" +
            "wLmRpZDowODQ5M2ZlMy1mMTJiLTBhNDktYjA1Yy0wNDU3MWI4YmM3NmIiIGRjOmZvcm1hdD0iaW1hZ2U" +
            "vcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiBwaG90b3Nob3A6SUNDUHJvZmlsZT0ic1JHQiBJRUM" +
            "2MTk2Ni0yLjEiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjA4NDkzZmUzLWYxMmItMGE0OS1iMDVjLTA" +
            "0NTcxYjhiYzc2YiIgc3RFdnQ6d2hlbj0iMjAxOS0wMS0xM1QwMTozNjoyNy0wODowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpiNzNiNjlkMy01NmZhLTE" +
            "4NGMtOWRmNC1mZjcyMDdlNTZlNWYiIHN0RXZ0OndoZW49IjIwMTktMDEtMTNUMDE6MzY6MjctMDg6MDA" +
            "iIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3R" +
            "FdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHR" +
            "pb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz54svuHAAAUIElEQVR" +
            "42u2cWZMex5Wen5NZy7f2vgCNlQAIECRAQeKQlCVLpmfsGckOWTMR9oV95Z/gv+J/YV85bI/H9jiCHmp" +
            "GIqmV2Bp7Y+l97/7W+qoq8/iiqhsNSKMBEWhH2NMV0YiOWjKr3jxbvu9piKpydPzthzmC4AigI4COADo" +
            "C6AigI4COADoC6Oj4XUfwqjemf3Lt/6uSO/qfX8kbBQgOjqdHFvTbhx652O87rM+eg+QtikHs/xugqS+" +
            "sX4yW36CHAJDmpR1JAY7PkTwtPM9YMAbEgCq4HLwDEbBBcU0VnAPvEFVUpLjfmuJ5EfAe8qx4f2PAluc" +
            "PPLvn7Pry2N6Bc4iCltFgbx4lRq3FiCuePQyAtEx6KhYfgOQ5Ji0A0jAqXlsUVBGfFx8qpvgQI6Ae8Rn" +
            "kOXhFjICxqATFdUxxT54VHxwEqClBxIPPn19DEGNApLgHRVwOWVYuoeyZDmIMakPAltCUC/zGAZKwHFS" +
            "Rfhd36hzJB/8ImwyI7l2HjSW0u4uvVPFXvgunL0Lex967gX14B602yd77kPTCZfzYGKa7i11aJLx/h2B" +
            "5Hk3a5CfPkF/7CK1WkYU5gidz2M11iGP8ex+SX75G3qyj6QCzukJw60uCpacwNIZ77w/Izl9GKxFYULF" +
            "QG0J2WwRf/oRw7g5YKVZa5DAsKAA8Qo70uqQTx+n+839NkHnkv/9H7C8+RTeXyRtDZB//Y/w//GeYxQf" +
            "E3TZmaYHs3BWS7/+I9Oo3cVOT2NYGdmkRX//fSPoZ8vg++dAo/R/8K9zEFPYnf0F1cxvaHfxbb5N/74d" +
            "k3/5DsorBpylmfZPIGqI0IYhqDN7/mN6P/g0agfRbSO7RkWnM0jLVp48IHt0EDUqADiFIC27f0UQCTJJ" +
            "i1pbJJ2ZIjp+mGlYI+w5JDGkck5kB8dwssruFO3eJ/ic/xJ27RPXBbeSXO7hKhfTyJZLvfAdNu1Rb6wR" +
            "Jr/AgtQTOIs7jTp5l8IN/iTt3GVl8RHz/K6Q2gnvvH5B/8qfoyDjm1z9D8h6QYubnCe7eINjewpgKdLr" +
            "YhSelG5cx1B9ami+Dmw0w3Q7h3EOSsUmyM2eJ6k3CuAHjM/ihcXyvjb3+BbR3SD/6hOwb38D0ekRffkp" +
            "wd5bs5Cn8eJPs7AUGH3+P8PEsptOCdIBJBtgcCCPyEzOk1/4A6Q+If/E3hL/6CTI8QR7W8KfOozMX4Na" +
            "vIM+QpE+4uED8qy8wT+9jOn2QEBn0ERu+VqkSvFbetAYz6BMtL5JnA/zkOK7ZJJuaxr19ET80jt1uE84" +
            "/Rit10tMXIFLso/vo/Zvoo9sY3yGevQljM7iT50iPn8A+6SH5AEkHqChaq6L1KoonXHxKdOcWsrmNdtq" +
            "Yz/+CaPEyxikmHaAmggwCHxCowWUDfH8XQ4yIQSQA8sK/9LABMhZJE2RjHulso8MnYGSY/Ox50ktXUKs" +
            "E808wnS55fRzXGMaFFYI0R7p9TK+P9hJ0ewd6fZhsQtwAGyOA1xQnGTaIkWgYoiFIM2xrHcm6MHDow1n" +
            "C5SUkrKCDDgQRxDWyM+fwn/wA99HH2E6HcGEJe+MXyPIzJCpjEHLYFmRh0McsPcZsrcLpMzA6hauNkp1" +
            "/B9vbIZq7jck9GjdQMYgLEB8iNkCCCGxUxAOXQZYgXhETlaWBw5MXC2HiIkWrB80wViDL0Z0dZG0Zohg" +
            "3OglRXGS7xhA6OQ35KCT9wmjuVVCXl6leDt/F1FokSbCLS8juLhpXoDYKFYOOTGDmlgkX5pHcQRQhYgg" +
            "HQpQq2ByMw4hgqhWoRHgcuh85Zf9HjaKk4HqIS1CvqBpQW6QMayCyRda2AXglnH9K5a//HDM3i2nvICr" +
            "4dg9TqZcudugxSIuMkGaYQZ9gcR67uoY7fgrfHIahBqa1i1ldQrIEcX3o7aI2wFXqBAgu7+E1Q0cmoT6" +
            "K9HeRbhtJB0UhWNYpkqeIS0E8NIaQoQl0fQM1Ae7M22QnToAV4qePkLQPPsHubhI+fIC5/nPY3UCHxjC" +
            "NCSSO9qt7PTwX0/1KFmuhItiFJ4R3buHOX8SdPAMuRbo70N0FN0Baa5ilObK3LsH4KMHkSXRrFTc5hTt" +
            "2EjERdnkJu7GOSQegHjWmSMhJgmm3kSRBR6dx59/Dbq7iq3XcR5+QvXsNWptEG+uQtMAlaBziJ6bR42f" +
            "RoTE0riB5hnEpYqTceshh1EGKqqBqwYNi8AGY5QXCubvk3/iYfPoYZmUes7ON2dxGjcWsrRNd/xX+4iX" +
            "8+Utkf/ZvMds/xo0OkV37ALO2TOWrz4mePcFNzkCtgTaGCtfs9QlWV4mXF0nPvkP3n/4p8fQ0vl5j8M3" +
            "voElCuHAPZxUXRvi4SXb2Xcz3csy5C6gq9FqYX/4lduEJNh5DVBDVw6qDihVATbEhNGB21rEPb2IfzBJ" +
            "YME9nMYtPYTCAehXTaRM+mEV//lfkqujoGDp+AnEpsvgY+9XnBDd/idnZwY0dxy48Qfu72M11TK+H3Wk" +
            "T/+wz/CAnG5/CzZxC4xDSDuGdG0S/+QKzs4PZ2iKae4gJInyjjj9xGqIY2VqBahXj/f5nyKGleaOoKIj" +
            "FKIADn6Hri8R/9Z8Jbv4UWhuY5Xm0UkEMiDWYLCH86U+xc8/QiWkkqCLtLkF7DbO+jLR28JUaptch/OJ" +
            "TbKNOsLaCpBm0OoQ/+wzmnxDMHC/Ck0CQO+zTx4Tz8+AVW31AYP4bYi2aJvgsRcMA6XawHYexI6gXVEC" +
            "tYF/Vc161eUH/yTuqFLtzFYNBMZqjucdJgK/XIQohz7CDBJNmJaVRUki5x0cVGGoiQQCDFGl3IB0UlIc" +
            "IhAFSjcFEkHlc2oK0h80NUq3hmw00qhRWsBefBgkahmijgTbrIBa8R1FULOoc9LaKrOujgu4wiv1ft+X" +
            "NW5BSkC3Wo+LxKmAixBuk14N+Ea0EB1ZQX9QdIgpRiDiH2dgEcagVhAiiCqhDA4AM004gN3gCfJygVRA" +
            "XYfMMu7WBigEVVAWsQWsVvHhI2tDbRdRgVEvrtjgj5FGCWov1RSwVdW/exZwEB1JkWY8YKVZetAhIUhB" +
            "Zfo8YMYUFCYKX8oMKaq8w9T3cjcUAoobcBBAWrJdIFfHFonhTzKHGFskUKfefimIL3kgUNYIHRC2YwqW" +
            "M1hAMiEXFofLqLvbKAAVhXBBX+MKK1JT13F7ws8+pvP1IqAcKv/L+wBXD7D//IuVtLeWzvqx8TTmHvFQ" +
            "EH6AO1ZdT7BFsUj6vB+4zEO5xQYdRB6ktwcmLyTwFRWr8c3XNGXBannNl0WdAgvJ3BcnBSfFjS+vzB0z" +
            "eFcmgyALlXFowmQXurgAELV9fiodUD4BuDqDuwRfvoXZvDPPmAfr3D54CHsWVO+KynhAtF7I8V9g3Ulq" +
            "WIvtxQ0TRoohCfOmi+8XnC6mjHPO5BWq5Cga/X8fsnRN8YYAqL1mI7o+/l1wog8S/e9NZ7MrkhP6Wacp" +
            "LFIsc8BZ9TlP/nRKbfD2FSX/XKxz0QH3pvr1rBx68tb7+hrPY2ffhayoC/zfUNH3FuV73PV6dkx4aL+P" +
            "h3y8B8ZUBMtmgAOjvWVfsUXfHm6ykvVfyPMerYoxgrcWIoIBzDl9uCK2xiAjOucLiDuhQRb1oEBFy5wq" +
            "Xfem6HAj0B2OeiGCkSOXe+zL5HbiOYMti1Dl3QAMrxERjDMYIIofEB3n15M7hvMcagzGmUC69xzlPnrs" +
            "iY4SCweyDKS8AIEggGAPOeZxzL1w3IvsfpVq49B7GRmSfNXXOFyAdSIIizz8+z4vFERFUFWNM8ajYr6M" +
            "bfh2APGdmprh84S1GhpusbW5z6+5Dltc2adRrXLt8gbOnZkCE2QdztDo9rly+yNhwkyxNicMAr9AbpNy" +
            "5P8fW1g7vvXOemelJ8jwnDAO8Vzr9AVmeY42hEgUE1pA7jw1DkjRjcWGRNMsYGxtjuNmgUa2UyrWlmyT" +
            "cu/eQPM+5+Pbb1Ksx6nNq1Sob2zs8ePyUpbVt+oP0cPig08en+NEffZcL589w894jdra3WVhapRJHfPf" +
            "D9/mj73zIIHf8h//yP5hf2eBf/OATTh+bZHlxGe8dSerY7fbZ3t7B4vnj73+bq++cZ3l1De89/UHGTrt" +
            "DL0mJwpDx4TqTYyNUaxW6g4xHT5cg62NtwLX3r3Dy2CSV0NLp9ki9stvp097eIgoD/uyHf8hws8bO9ha" +
            "VSpW1zS2mJ4b57MubPF5cPYQ0r4LzhYulHsQEVOOIMCi2DJV6kyCK2WlvkqbZfoG2vrXNl9dv8ejpIuv" +
            "bLYwxbG5tMzEyRBQGbGxu88Wvr/NofoXtVocAh88dYRQyOT7Kt65c5r13L3L37gP+619+xuLaJpfOn+N" +
            "q7tlt7XJjYZGvZh+xvt0iCAO2N7d47+23UJexurnNr2cfsLqxxcmpca5evsTj+TWeLKwcAuUqBu8hy3I" +
            "GSZHyh4caTE+OMzw2RqVawyOkudsPzs55WkmXhcVlbt17xLOVdcIgoBqHTI2PgMBuu8OT+SVu3p1jbXO" +
            "H2IJzOWEQcnx6iqnJKd6+kPN0YZkvf3OLfuY5Nn2cLM9JBinLq5vF2IurDDVqhGGA85BlGbvtDk+fLfL" +
            "gyTNq4bvMfPsDRoeHkMNofynaeYrgmSUJeMfQcJPTp04w3BwhCiy5c4RhiLUWVcV7TxwGTI4Oc+7UDDY" +
            "I6PYHuDxDfQFgJY4YGx3hrZMz1Gs1Or0erU4PEYsNqxgblfvQABtXiSUnsIKixHGNqckp3jp9kigICK2" +
            "l0+vvB+/YChP1iHRymNFGlX7SZ7Bn3W8aIH+gQNxudeh0ezTrVU4fn6JWbeCzAd12q9halpkjz3OOTU/" +
            "wwTev8v7Vq8zNr3B99i6PHj8lz3OSZMCpmWk+/tY3+PYH32JhdYMvb8xy/fY90v4A7/VAdir7fTQvREB" +
            "VarU6ly9eZGb6GKvr6yytrPKbW3dIBinOOSbGR/nm+5e5kr+N98qdew9ZXFnd29q+eYDECKqwsbXD9m6" +
            "LWrVGtVonDCPyLKXVblOr1ffrGtWCk47iiLgSMdRoUq1UsPuklxIEhlq1QhhVaPYTqlFEYISs3F3uZX2" +
            "z14eFHqjmPWEQ0GjU6SUJ8c4Oxli8erwvADw+E1CtxKyvb3Jr5R7dXu+QCkWxiClcp9PapdvuMDw6Sq1" +
            "RI7CWdJAxyJVqWbAZY4iikNW1DT777HMePltlaX2bJB3gspSpyRFqtQobW1t8+tef82h+lfWtXZJej36" +
            "3jw0ijLH7O/WCRDUFsxkUam27vcujx8/4+fU7zC+vY6whTRJOzkxhjdDu9ljd2CaKQupxyKULb3HzwRM" +
            "eH0qQxmNKbqWbpCSZ43glZnp0BKfKfGuZdlsYGWrsF2vGGPq9AQvLG3x1a5bFtQ0azQYjzTpGDEEY0e0" +
            "PmHs2zy9u3GNzu8NwLSKKq9QbEaGFwBzoiyyb66Ts9RkMBiytrPCbW7PMza8yPjbG6FCdIAiw1tBq97j" +
            "z4AlLq2tcPHeaj69dZWxkmMgeggUZfBH9RchNgDMWI0olsKTO097dwacDdGa6AKgM0tVKlampaU7NrGM" +
            "MRHEFA3jnyXMIw5ixkRFOHjtGHHeIrJJlhVZvxGGl4L9VSyUFjylJ9yAIGGo2mTk2Ta6WRr1BIL7okxR" +
            "hMEiZX1zhJ1/8klany7fev0KtGlOLg8NJ83GlSnN0lHonoZsMSNKcTAsiudvvU4kihpsNatUq1lqqoWV" +
            "ibIwPP7jK6TMn2d3ZJc8G3L7zAO+VMAg4c2Ka7330AZcvvctWJ6HTbXP7zn3mF5ZI0wRrheGhJrVKVGh" +
            "w3mGMUK9VOTE1Ti2uMDI+SbufIQqzs7eoRwHDQ018IabgsgHiHcPNGuOjI4yNjR1CoYhhc6fF7IM5Vja" +
            "2Wd/YYnNtndWNLcIo4OGzJTaaLarNJktrG+zutrhx6w7HpsbZbfcIo5CRkRGSfpcgDNnc2eXG3ft0ex3" +
            "6/QHVSsyIDUCUqFLBA61un0fPlhi+cZvF5RXCwOIxtDp97j9+Sr/bxlhLFMVMVGu4wYDQCOsbm9y4fY9" +
            "2r8vWzg5hFNLt9rh+8xZLK+vk/tU3Y69Mub77/R9rsxoy2ojJVOgPMtwgpVYJiKKQ3e4AjKVRr9Lu9HD" +
            "ZgNFmnTgKyJ0nx+JUUDy9Tp8sz2k2G4W5uxSHJdciS3Z6Cb1+ggUatQr1Ro1+P2G31SX3SrVaYahZpWq" +
            "Lpcu0cHfjc3Z2OwCMDTdInWe73aeXeZqViInhCt1+Rqef8etP/5O8UYAuf//HisuKjg0b4lTw2QCDYgO" +
            "LI8BpUQ5YY7EGfJYWwd0U0UPFFo0hxqIIaZ6BOkIpqXQxWCuIFP3T3ntcnuF8ThRYorBousq9J88zRPO" +
            "CwDfhPrWv5b/qcjyCmBAbxYh3+KyPmACxAXf+5s/lDWcxEGsRU8ErWCNEQfV5vQPYMozu0QliLKIeU7a" +
            "/77edmEK7isNov3Nkr3YTcYWqQUFRmCgk8KaogdQBplCLrC2oi/0RijSyVythQ6wIsqdkGIONamX7y6F" +
            "kMUcp2qCyn3BL5cnvddmWPQ7FyuYSFKlZXVEkiGBRFIeUz4qY/d/3CsO9+fZEgkKt3VNb/b5GWKgVini" +
            "HisUYi9PnK2ZEy/blkk4z5Z816KEAxF6iPyCIygu6jbykpRbsoCmVTXlRginv3LtvzxKLmfSFDeXBM3J" +
            "gb/i8MVn2rXBPIzvQyHcg08iBud94JW0QBXNg8L34ZcpSV8uv99iiYQEp2mUI9l9YVV6iUfQF3VD1t6X" +
            "hF87o80/WMubs0b57A8nfOtYh9kmrPqc1/65ONEql1TwPLL9XDX+Jtv5ah7ykWMoLEv6L877OPK/XBvx" +
            "7X/Y1nnttcH6H0vt73uJ15pGj//3lSBc7AugIoCOAjgA6AugIoCOAjo4jgF7j+D99GSBZeuFOzgAAAAB" +
            "JRU5ErkJggg==")]
        public string VMDefault {
            get {
                return ((string)(this["VMDefault"]));
            }
        }
    }
}
