//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceMeeter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Plugin : global::System.Configuration.ApplicationSettingsBase {
        
        private static Plugin defaultInstance = ((Plugin)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Plugin())));
        
        public static Plugin Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAABS2lUWHRYTUw" +
            "6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN" +
            "6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWR" +
            "vYmUgWE1QIENvcmUgNS42LWMxMzggNzkuMTU5ODI0LCAyMDE2LzA5LzE0LTAxOjA5OjAxICAgICAgICA" +
            "iPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW5" +
            "0YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp" +
            "4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+IEmuOgAABGNJREFUeJztmu1PW2UYh3+n7SllHRuFlkL" +
            "MWKgbERZmFTBREiOaKEs0jiUzQqzRwAKRzAX85P+gGGPMpiHROE1NpilGFhLnMjIzl4gSwoIl8lLpMrO" +
            "udC0vLfQN/NDIPLTlLsLpOSb39a3PaZ/z65We85znvivUVhs2wGRFo3QAtcOCCFgQAQsiYEEELIiABRG" +
            "wIAIWRMCCCFgQAQsiYEEELIiABRGwIAIWRKBTOgAAlJn34ZmnKnHUZgIATM8FMfKzF/cWIgonAwQlS65" +
            "6UYve7ka0nayBKEp/zPH4OpyDbnxwYRSxeFKhhAoKEkUNBvpPoOHR8m3fNzp+F2feGUY8vp6nZFIUuwf" +
            "1dT9BygGARns5+roa85AoM4oIslqMaG+tyfn97adqYbUYZUyUHUUENTdVQqfL/dQ6nQbNTZUyJsqOIoJ" +
            "sh4vz8pm9QBFBWq2Ql8/sBfygSMCCCFgQAQsiYEEELIiABRHILshcUghzSeH/Zt6tyCrobGc9RlztGHG" +
            "142xnvernzYRsgiqs+9HlsEMQAEEAuhx2VFj3q3bebMgmqMgoQvjX7kAQsLkjj0Z3XgBLJlNlK6vFmDZ" +
            "vkVHcVdbtkE1QaCmaNlZRlhLkub244/nm5kMAgHLLvrRji8uxHc+XK7IJ8gciiKzGJWOP1VkBANdvepF" +
            "I5F4hTCTWce2GFwDw+HFpkS2yGse9hfAu02ZHNkEbG8DYhE8y1vJsFfSiFj5/BM5Bd85zOQfd8PnDEEU" +
            "NXmiukhwbm/BhQ8aisayr2NWf5iWvS02FaDuVqiT2nx9NE5iJsQkf3j//CwCgrbU2bWnfeo69RlZBQ1d" +
            "msRKWXmZvd9SjrsaCWDyJzr5hOF1uJJPpl1syuY6vvv0dHb2pgn21zYRzW5b0lXAcl3+clfMryN/V6H7" +
            "dnvas4g9E0PPuFUxOLQBILd3NTZU49NABCALwp3cR12544fOn7i3VNhM+ea8FZWbpDfqjgd9w4YtxOeP" +
            "LL0gvanFp4GUcqTJJxteiSXz46Sicg+6sLR1R1KDtZA3OnWmAwSDtcU57gnil8zvZe2Z56YvZDhfj4sc" +
            "vovhAQdoxfyCC4atzGLvlw1++FRTotbCajThea8GJ52ywlKYv66GlKF57awgeb0ju6PlrHD5ytBQD/S0" +
            "wHTTsap7QUhQdvcOYmg7sUbLtydtufmo6AEfP5c0Hvv/C3HwIjp6hvMkBFGg9F+i1eOPVOjhOH8v51xR" +
            "cXMPFS5P4/OtbiMby26dXrDdfaNDhpeeP4OknD6HBXo4io15yfDkcw6/jd3H95m18/8MMVtcSSsRU9t8" +
            "d/1D9cAlcn7VKxlrfdOGP2fsKJXqAOiqKmfYKcu4fdoAqBMUzbFwzjSmBKgR57yxjxhPcfD3jCcJ7Z1n" +
            "BRA9QxT0IAEwHDXCcPgYA+PKbSdwPrSmcKIVqBKkVVVxiaoYFEbAgAhZEwIIIWBABCyJgQQQsiIAFEbA" +
            "gAhZEwIIIWBABCyJgQQQsiOBveBtImNHT9L4AAAAASUVORK5CYII=")]
        public string MicEnabled {
            get {
                return ((string)(this["MicEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAABS2lUWHRYTUw" +
            "6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN" +
            "6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWR" +
            "vYmUgWE1QIENvcmUgNS42LWMxMzggNzkuMTU5ODI0LCAyMDE2LzA5LzE0LTAxOjA5OjAxICAgICAgICA" +
            "iPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW5" +
            "0YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIi8+CiA8L3JkZjpSREY+CjwveDp" +
            "4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+IEmuOgAAA8dJREFUeJztml1z2kYUQI8AC8JXbIINZNK" +
            "mcRzHzkP6/9/70qfOuCkYgt00jUHCfNkYEEJYfWDcoBixkJGQMrPnDa20unPYvezeRXl3nLCRuBIJOoC" +
            "wIwUJkIIESEECpCABUpAAKUiAFCRAChIgBQmQggRIQQKkIAFSkAApSIAUJEAKEiAFCZCCBMSCDkBRFEq" +
            "FLMX9DKmUCjYMxyZaa0BTv8W2V5fMC/kMR4d5FBTO6zrt7tDb+IIs2qtqjF/flcikE0vbb+8Mzv5qYE5" +
            "nS9uL+xlOj4soyvyzOZ3x2++XnsYY2BRTFIX3K+QAZNMJ3h4dLG37Vg4APnzVgQl6XsiSXSEHwJhY1P9" +
            "uP7q+TI5tQ/Wi5XWYwQkqHmRXthsTiz/+/MLYmDqfc5FTrmlcd+48jzMwQemU6tr2PXL064EvcQYmKBp" +
            "d/uowyYGQrYPCJgdCJCiMciAkgsIqB0IgKMxyIOCtxsZyqhp6e3tyIMARtIkcCEYOBChoEzlAIHJgC1M" +
            "st5vk9LgAwPnHFp3efLe9iZxF8rkUJ28K2LZNpabT7Y98ifsB30fQydEBcTVGXI1x+DK39J515QCcvim" +
            "g7kSJqzFOXDayXuK7oGhs/gpjYvHhXHvUvo6c2ex+3lc0ws5O9GvfLqtxL/F9ipnmjNnM3jjnLDIcmQA" +
            "k4s5wp9byOpGX+C6o3R3S0G6+Ww6A1pon6L3dpOP6aDxddrun+C7o4tN69Rw3bgcGV9oNiqLwovTU0db" +
            "zOUFDAD/zG8m5MzirNLFtmxelpySffC2R2LaN3va+/vMtW11Ju62QP1/1yGYSpJMqkYjCYDhxFO1zu0l" +
            "ev8o7+tJaA0zT8j3mrQlyGzmVjzpa63bpM4qi8NPzXV7/kiey8KBl3XP5T8fPcP9nK4JWTatXP+eIq1G" +
            "6/RFjY4qCQjwe49leklIh65hWD1TqOpMtjB7YwrHPJjlnHaoXLa6aN950tga+jiC3nGNZM8eCbx0s655" +
            "KXed6C4l5Ed8Eucmp1DQ6vRGHL59RKmYduWUZtm2jXQ+4/NTZ2rRaxJcptkqOtlDsUneiHOQz5PaS5HM" +
            "pRx/t7pBef0SrfReImAc8Xwft59NryYH5UfGXZp+zcuNRP2flBv82+oHKAR8EvT3cX0vOj4KvK+lN5Cz" +
            "u1YxJsKNmEc8FlWs6Y2PKxLT4UG2uPXKq9Raj8ZThyKRce1wWCYpA//7yIxD4sU/YkYIESEECpCABUpA" +
            "AKUiAFCRAChIgBQmQggRIQQKkIAFSkAApSIAUJEAKEiAFCZCCBEhBAv4DqwLesGtEvG0AAAAASUVORK5" +
            "CYII=")]
        public string MicMute {
            get {
                return ((string)(this["MicMute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF+mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAxLTEzVDAwOjM2OjU5LTA4OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMS0xM1QwMDo0Nzo1NS0wODowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMS0xM1QwMDo0Nzo" +
            "1NS0wODowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDpmZGY2MjAyNS05NWI2LTAyNDAtOGNiYi1mMTY3ZGVjMDhiM2IiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDpmMDYzZmFiZi1jNmFjLWNhNDctYjQ4Zi0zNDc2MTY2NmJiNGQiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDoyZjNiMjQwOC0xMWIxLTI2NGMtYTdmYi0yMDI" +
            "1ODMzZmQ3YWIiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjJmM2IyNDA4LTExYjEtMjY0Yy1hN2ZiLTI" +
            "wMjU4MzNmZDdhYiIgc3RFdnQ6d2hlbj0iMjAxOS0wMS0xM1QwMDozNjo1OS0wODowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpmZGY2MjAyNS05NWI2LTA" +
            "yNDAtOGNiYi1mMTY3ZGVjMDhiM2IiIHN0RXZ0OndoZW49IjIwMTktMDEtMTNUMDA6NDc6NTUtMDg6MDA" +
            "iIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3R" +
            "FdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHR" +
            "pb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz5jHZL4AAAKT0lEQVR" +
            "4nO2de5CWVR3HP6AChRKaY0qWNThK6DhtRl5qHGWCwEgpaPIy0ajhYBcYwsiabkY23ZQkp7IyL5NLpU7" +
            "QxcoCGzPdws0aEdBkukgamUFrTGHF9sfhHZZtn+/v2efseS7v+/vMMMzu77mc2ffznuc5t98Z1d/fj+M" +
            "UZXTVBXCajQvkROECOVG4QE4ULpAThQvkROECOVG4QE4ULpAThQvkROECOVG4QE4ULpAThQvkROECOVG" +
            "4QE4ULpAThQvkROECOVG4QE4ULpAThQvkROECOVG4QE4ULpAThQvkRHFgioueseQPKS6biuXAh4CDgV3" +
            "Ap4AVlZYognuuPabU+yURqEHcClww4OfxwMcINfOVlZSoYXTyI2ywPANZBIwtsSyNpVNrICUPwETgEGB" +
            "34nLMBE4AHgLWAY1LldKJAlnylMEE4C7glAG/ewyYBWytpEQF6bRHWB3kAbiF/eUBOBZ4GDiu/OIUp5M" +
            "E6qYe8rwQODsjNhZYTYOeDJ0i0K3A+VUXYi+TgINE/BVADw2RqBMEqkvN0+J3wDPGMScD3yqhLNG0u0D" +
            "d1KfmafFX4BM5jntjzuMqpZ0FqtNjazCfBD6T47j3A+ckLksUjXjOFqCq1tY8YBqhP+duQlM9i+XAScD" +
            "rjGveAHQB20aigCNNO9ZAVclzLXA78D7gCuBHe39WzALuM445HPhKdOkS0W4CVSXPucDiIX4/D/iece5" +
            "M4AnjmFnApQXKlZx2EqjKTsI3idjrga+K+C6CIP807rEKeMnwipWedhGo6qb68434JcB7Rfwh4O3GNcY" +
            "CXxhOocqgHQSqQ2vrhzmO+TShpsmimzDEoZiNru1Kp+kCVV3ztPgy8GiO49YCk0V8IfZgaq0muzVZoDp" +
            "1Ej4LnEboZVaMIcimrvNh4xpTgYvyFy0tTRWoDo+twfwNeDWw0zhuOvAeEe8G1hjXuDx3qRLTRIHqMiV" +
            "jKJ4E3pzjuKsJNUkWHzDOnwpcnLdQKUndE3048Bzgv5HX+TewA/ga9ZWnxU8IteNq47irCONdQ7EZWAk" +
            "sFecvI/w9KiWlQO8m9F0A7Bmha1ZVY84nfGATCIJcSXhkZfENYA5woThmLuHL0J0RXwm8g+y52VOBswh" +
            "DJpWR6gOZzj55WvcZiX9l0qo1VwC3AacSPrTFhJ7jLuP8dwHbjWPUu8zj2P0+C414clJ9KFlVc5PYARw" +
            "JfHCIWGvm4CHi/J3AO417dKFrqWsIj+8szgdeatwjKakEel6i65aN+iIcTxgIPUAccwdwp3GPZSK2Dbj" +
            "OOH+2EU9KE1thZWKtDTsRe6R8MXq5Theh+Z+FNaI/14gnxQXS5JlWehGwRMS3Al8yrqHGye4D7hHxGej" +
            "e7aS4QNlMJLws51nifBVwhIhfja6FZhNWa2Sxxrj/G4x4MlygbFpdHB8FfmAcO57Q7M7CqoXGAG8Vcev" +
            "+rzHiyXCB8nE2enoqhD6dV4q49a40XcS2AD8X8RnAocb1k+AC5ec84C/GMapf50HglyJ+FnC0iKuZjRM" +
            "I68lKxwXKzw700ALAW9C10FoROxDdJLfmTk8z4klwgYZHN2EoQ3GJiFl9Qqo530tYU5aFC9QQVJMdQuf" +
            "juIzYr/f+y+I0EdsFbBDx42WpEuECDZ9N6FHwF6Cnrqo+nePQIjwsYpMJsx9KxQUqhjVVQ/XL9BjnniR" +
            "i94rYOELPeKm4QMVYD/xRxE8VMdUSAzhKxP5snHuYER9xXKBi7EGvxJhCSOMyFFuB34tzVafgZqBPxEs" +
            "fmXeBivNdERuNroXuFzE1gNsHPCXix4pYElyg4mwx4keK2L9E7BTC0EbR+5aKC1Scx4CNIq46FNVa+AM" +
            "o/rkoaZPgAsWRZzHhUGwa0VLs42WJrpuJC+RE4QKlo12Td+2HC5QONeG+bXCB0rGj6gKUgQsUx8FVF6B" +
            "qXKDijKP4JK5UU1BL7yNygYrzYvTo9wMiljXdI5YnE103ExeoOIM3SxmMGvhUKzh6yO6pHkdFE8eycIG" +
            "Kox5De9DTNk4QsWdFbAy69lIJH5LgAhVjNHrS2Bayhysmo7Ot/kbEjiJMoM+iV8SS4AIVYybhHSgLVfu" +
            "oUXrQ7zFTjHNVIoYkuEDFWG7E1VQPNXEe9Pov9djcDfzCuPaI4wINn9mENVxZbEdPNlMT558Afivi6t1" +
            "pO/C0iCfBBRo+VoLLG8luRXUBLxfn9pL9GBqPboE9SnwqwWHjAg2PJeglyBByAmUxxzhXrdg4Gd3vpB5" +
            "9yXCB8jOFkDFM8U10B6IlkHr0nW6c6wLVnC9i/70+K2JnAK8S8Q3oGY5Kvj60uMlwgfJxF3Cmccwq9Id" +
            "4nnH+d0RsCrr19gAVjf67QNm0XmZvJqRPUWwHPiLik4FFxr1uFnErD6LqNkiKC5TN3wlruxbkOPZC9BY" +
            "Hy4BRIn4nIa1vFnON+//MiCfDBdK8NscxK4F1Im7VPqA34D2d8P6UxUYqGMJo4QJpVF5DgO+jN04B+Dy" +
            "69ulFt6DmG9e/0YgnJZVA6xNdt2x+LGKPYO8YNB/7/UXlVjyakPFe8W0jnpRUAt1E+HY2mUMJc3qGqmE" +
            "eIfQKPyPOn4idJLyHsPtQFsuAg0R8NfYeZUlJufRkDuHl70zsPbQs+giJA6xv40jSykC/krCF9wLguYT" +
            "9TW8hDF4qriPkClKoLPUvAi4zzq98O/DUa5fWYOc4Hg4bsZN2p2ATYS/4vFyG3gMDwo4+Ku/hUnSihR4" +
            "q3qkHmvcSfT12i6ZqZmDvsrMbPSh7InZCz8prH2ieQBAksqr2qpiEvbcFhC/Bn0Tc2ljXSrNXGk0UCMJ" +
            "jrG410WGEFHRqyikEwW4S8bdhdxyqMbdSaapAUK+aaAwhaZSVIexpdJknsf9GfUNxLxX3/QykyQJBfWq" +
            "iSwkZVi3ORed6XoVdg6kxt9JpukBQj5pIrdBosRTd47wImGdc4+vUrJO2HQSC6msia1Ph5cDnRLyLMN9" +
            "I8RRh87pa0S4CQbVN/BtErBs9WDoJ+GmOe1xBDTN+tJNAUJ1Eawmbyg3mduwOxduw33vuoCbN9sG0Yxa" +
            "t6/f+X3aP9eWEOdFzCX/Xddh7jN2PvdBwG3BxbOFS0Y4CQZBoFPZ7xUizAb0hykDuxpYHQg2mkotXSrs" +
            "9wgZS9Yu14uPYc6whvHyrpT6V084CQT2a+IM5AnucC8I7j3r5rgXtLhDUryY6hjAtRLEBWFhCWaLpBIG" +
            "gXjXRP4z4rwjzoK2+pVrQKQJBfWqizWTvndpLyHz2n/KKE0cnCQT1mU+0gP/PIbSesHiwMfJA+zbjFVX" +
            "1Ew2kj5DmZRoh58+D5OuNrh2dKBDYEu1ET5gfKYbTb1RLOu0RNhD1Yr0Ce9K8Q2cLBKEGuoB9c3QeB87" +
            "BntPs7GVUf7+1+NJxsun0GsiJxAVyonCBnChcICcKF8iJwgVyonCBnChcICcKF8iJwgVyonCBnChcICc" +
            "KF8iJwgVyonCBnChcICcKF8iJwgVyonCBnChcICcKF8iJwgVyonCBnChcICcKF8iJwgVyovgfTXWQa0J" +
            "v7VoAAAAASUVORK5CYII=")]
        public string SpeakerEnabled {
            get {
                return ((string)(this["SpeakerEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF+mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAxLTEzVDAwOjM3OjAzLTA4OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMS0xM1QwMDo0OToxNC0wODowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMS0xM1QwMDo0OTo" +
            "xNC0wODowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDo5N2Y4MDc2Zi00YTEwLTMyNDctYmE0ZC02NjYwMDQ2ZTNlZTQiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDoyYmE2MWQ0NS1mZTc2LWY1NDQtYTFiOS1jOTE1NmQzZjE5YjUiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDowMmFhZTkwNi01ZTBhLTliNDYtYWFhZi0xZjg" +
            "0OGQzY2Y1YmIiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjAyYWFlOTA2LTVlMGEtOWI0Ni1hYWFmLTF" +
            "mODQ4ZDNjZjViYiIgc3RFdnQ6d2hlbj0iMjAxOS0wMS0xM1QwMDozNzowMy0wODowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo5N2Y4MDc2Zi00YTEwLTM" +
            "yNDctYmE0ZC02NjYwMDQ2ZTNlZTQiIHN0RXZ0OndoZW49IjIwMTktMDEtMTNUMDA6NDk6MTQtMDg6MDA" +
            "iIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3R" +
            "FdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHR" +
            "pb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz55tAq/AAAKq0lEQVR" +
            "4nO2dT4zdVhWHf+f4/U+aZCYlaRWgYlFFQUVt0qaLBiGxAKEWECA2jQRiw5YVAiSQWLFoJFhX7EBqERs" +
            "EtGm7oIJNJyUEBSiUlqhCQCUUhaaTSTLz3vO997Dw82T+5D3b79pj+/l8kpXRzHu2M/O9n4+vj69JRKA" +
            "o88Jl74BSb1QgxQsVSPFCBVK8UIEUL1QgxQsVSPFCBVK8UIEUL1QgxQsVSPFCBVK8UIEUL1QgxQsVSPF" +
            "CBVK8UIEUL1QgxQsVSPFCBVK8UIEUL1QgxQsVSPFCBVK8UIEUL1QgxYtWESv93rlzGN5ax+2bt+DEgYh" +
            "yWW+r3c5lPTEcMMS6T4xGox8x84NEdGUcjr65fODe3+0fHICxYa7bSw+BmXD9xv8wHA8RcLDtpyKCVtA" +
            "CM2M4HqLb6QEAwnCMjeE6fvrss3u2p4UIVAeICCY0T1tjnmeOglhEHm0F7d+OwuHnzS3zQpnzBhAI1lo" +
            "wVfsg0UiBiAjW2qetMc/vTEcixnA0/K7AvQDkk5zzwsQgYgDVnQCjcQIREdwUeSIEzHwc4AMA1vZ6/3Z" +
            "TXXmAhhXRsTxmqjxKVhqTQLMOW3fBTRYlgUYkUPJhS5mXhU+gjMmjZGShE0iTp3gWVqBJ8pzVgrlYFlK" +
            "gSfKctcY8p/IUy8LVQHHylCnPPNut62y5C5VAW2qeWslTZxZGIB0kLIeFECg+VS9PHmpc8sTUXqAqnKp" +
            "Lgweta11EV2mQsK5FsC+1TaAqJE+8H808eEXUUqAqDRKWvf2yqZ1AxFyZQUKiqHhu5sErolYCxSPMpgL" +
            "yxPvT0NJnk0KK6CBgUNRnzIAcBiiAX3+NENE1Z+1XrbU/qYo8Ec02qBCBwnGI8Xh0xjr7HDM/ACCEZ4O" +
            "WiMAY06mCPIDWPjGFCLR67fox6+wrxLR/8q1c7sepyh+tKvtRBQqpgaw1nyGi/Yt6gqsC3aEQgYh5UMR" +
            "6q0Bl5SlptwoRSEQWdmx/hkDHAHwRwOk93BkAOA7I8bJOB2t1Gl820+Qh0LcAvAvgFyJyUUT+COD+Ivf" +
            "DiTtujHkjYH7LGPOWtfZNZn7Yub397KpAGRAROOd2Ll8G8MyOl54SkT8D+FBBu3JSRP7inH0oPnaJyAk" +
            "AF9qtzgMFbfOuqED+fG3K9z8gIn8A8OGct3cKwOsAdg1piEi/3+9/PeftzUQF8mdWyhwVkUsJr8nCI5j" +
            "IM+0FzrkP5rStVKhAGRGRbYtz7nJCK0deSXQSkTwzx9SI6E+e28mECpQSEUEQBGi12giC1ubSbnd+AGC" +
            "cULwenUg0bzqcBPB7AN2E1/3LOrt3kwOh5g1le4lzDq1WGwcOHIS1dvP7zHxlNBp98saN66855xDPNXQ" +
            "XjojIJSJ6HMC/M2z6JIALSE6eVWvtp0MzHmZYtzeaQClhZmxsrCMMQ7RarTutHCLo9wcrhw4tn4nP0mY" +
            "QJ1Hamig+bCUlz00iehyEf6Rcb26oQCkhIjjnsL5+G8D2WsiYEL3eYGVpaatEUwccj6QsrGN5phbME1a" +
            "J6FGArmT47+SGCpSBIAgwHG5gNBohCLbPWxhJ1F9ZWlp+IpLITlkLgEiiWUmUVp61ySHxSlltJSpQBuI" +
            "U2ti4jbsljDEGvV7/wvYkmsrRyYj1TomyJM9jAEpJnhgVKCNRCg0xHu9OISCWaLCytHT4CRGRBIl2nuJ" +
            "vDhIm7MaNO8lTLipQRu6k0Dqm1TmTw9mFpaXDH0+ZRL8G8BSAXyGdPKdRAXkAFWguohRan5pCwK6aKCm" +
            "JHgbwIpLHiSolD6ACzUWUQjK1FoqZnJ2lTaIk1qomD6ACzU1SLRQTSdRbSVlYT2O1ivIAKtDcbD0jo8m" +
            "E4NMWax0Gg30ry8v3nonfl4Gbk4I5YZCQAAhkj0/nixKoon2f+RKn0HC4DiAa+5m2jEYjdDrdlXvuOfg" +
            "RIqylvJf+n0R0DKmSRxA9IGFvf/V6LcyDqB9HsLa2CqYg1aefmUfMgU0pkAEwSvNCEQETo9ftp3l5bhQ" +
            "lUEPutos+9SKAFZPmDSeds68TcdKpesyDIvJudKkC/0l6MZWQQFoDeUHodnqbD0VJWE4RcRZ5YlL3E8k" +
            "C1UALj3UWnXYX/W4fdvZ1LyBFJ2ECeXc25oYKNCcigkFvACJO+tSn6CSMzswS7oYqqsfaCxVoDqy16HZ" +
            "66Hai9JlRdaTqJBRxb/Z6/bPMwdWCOxtzRwWaC8GgOwAxzZraLlUnIYBVEfeFXq/3s0OHlr+UYrAx7ie" +
            "qRBKpQBmxzqLT6aHb7cHZqbVPtk5C0BVrbXztrIjOxsJQgbIiwKA7ABNPS5+MnYTRIKHI1laQXDsbC0U" +
            "FykCUPl10u71tjfVbmKOTMCK6R1Dy7mwsHBUoCyJ30mf3mVdunYTzdjaWMXOICpQS6yx63T76vX0QF10" +
            "2YA7A0SSbuXcSenY27hkqUEoIhE67B+sMQhvCWANjQlhn7yPQqyigk3COzsZX0q47L1SglDAz1oe38N7" +
            "qNazevI7Vm9fx3o1ruL1x6xvMfCjh7XN3EmbsbDzhnPtK1m34oAJlIBotlp3LqYS3eXcSZulsZOY9Lah" +
            "VoAwwM4Ig2LYw89UZb8mtk3BrZ2PUe7RboonQ7/huKwsqUGoIxhqMwxHCcDxZRrDW/HjKG9bSdRKmJy6" +
            "sDx5cPhPfVh0z+fqvztmf57W9NKhAKZn0jsEYExXQ1iA0Bta514joSQDvx68Vkcsi8jEU0MNsTIh+v7/" +
            "S7XYfcs5d2vKjV/cd2P+pw0eP5L3JmRTSUCYiXNnZTOdERNBqteDEwjm3OV/i5J+Xieg+InrEGLMh4t7" +
            "gGY32vkS1GP5GhNNEdL911rWD9tV2u4NOL+nqSb4UIlC70xmbMKzulLgeBNyCc+O7/WgM4KKIbHYnF8v" +
            "m4eu/mw9dcA7OJPYm5Uohh7Ag4MuL2NQaTzLFPPU6GBbwMzOTQgQaj8YXOeDvFLHuKhCw3osQU8hvYvI" +
            "JfUZEfklEjxGRgd/DVt4H8FER+SFKvpMkTiHreNoF1UZR6B9DIG8T6O2cVvcbAO8guoe8dAJuqUAo+DS" +
            "+gELyPIDP5b3SrKSphZpCHceBXkQFJAKAINBaqI4CARWQSEQQcBDdkdrgFKqrQEAFJAIwc2aOJlBngYB" +
            "Ios+WvRNNpu4CARUprJvKIggEVCCJmloHLYpAQJREejjbYxZJICCS6KmyNh41dAFlPX6yDBZNIAB4CSX" +
            "VRCIC5uhujWzTrMjmszfqxiIKBJRYE9Hkdh/C7meLTV+AMAxrGVyLKhBQWk0kiGcuS0v8JKCkGV+ryCI" +
            "LBADniajyhXXSMziqzKILBEQSlVZYpyV+ElDdUqgJAgHAS1VPorSz31eNpggE1CCJ0s5+XyWaJBCQPok" +
            "YJfxu6lgLNU0gIN1gY3wqtefULYWaKBAQDTbOSqI3RORm+nGc/BYgmsQzSqHq0+SWuvMAnkQk006+X+a" +
            "ocBAEMMbAWoudtzBXjSYLBAAvA3ISwDmATgD4O4BvE9HlMneqTpc0qMp2K9WnqTWQkhMqkOKFCqR4oQI" +
            "pXqhAihcqkOKFCqR4oQIpXqhAihcqkOKFCqR4oQIpXqhAihcqkOKFCqR4oQIpXqhAihcqkOKFCqR4oQI" +
            "pXqhAihcqkOKFCqR4oQIpXqhAihcqkOLF/wF33aLSldTI6wAAAABJRU5ErkJggg==")]
        public string SpeakerDisabled {
            get {
                return ((string)(this["SpeakerDisabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAABGdBTUEAALG" +
            "PC/xhBQAACyZJREFUeAHtnXuMVcUdx3+77PsBLhgWVBYQebSigM80is8mxjStxme1xT/a/mPEGqDUxtd" +
            "faoyNRlCCGv/QaKRBjY+krbba+qyaCKy4GKjgyj6EBXYF9t5d9sGu8108Zr1753fv3XHumbnzm4Rcds6" +
            "Zub/fdz73nJkzv5lTNNC4bJgkiQLjVKB4nOWkmCgwooAAJCAYKSAAGcknhQUgYcBIAQHISD4pLAAJA0Y" +
            "KCEBG8klhAUgYMFJAADKSTwoLQMKAkQICkJF8UlgAEgaMFBCAjOSTwgKQMGCkgABkJJ8UFoCEASMFBCA" +
            "j+aSwACQMGCkgABnJJ4UFIGHASAEByEg+KSwACQNGCghARvJJYQFIGDBSQAAykk8KC0DCgJECApCRfFJ" +
            "YABIGjBQQgIzkk8ICkDBgpIAAZCSfFBaAhAEjBQQgI/mksAAkDBgpIAAZySeFBSBhwEgBAchIPiksAAk" +
            "DRgqUGJUuwMKNX/TQV1/3pfVs1gnltHhuVdpjoWYKQCkt//qHh+iVd75JyT3255UX1glAKcrILSxFEPk" +
            "zNwUEoNz0krNTFBCAUgSRP3NTQADKTS85O0UBAShFEPkzNwUKCqA9BwbomX8cyE0BOdtIgYIZxm/7spf" +
            "+tLaVvukepM6Dg7TyxmlGwtgq/N9Nh6luYknBPA4oCIDe3dJNdz/ZTn39QyPtvvGtrpFP1yD6zyeHR+w" +
            "smUD04PIGOvfUaluc5q1e729hHzcl6I71bd/DEykHiB5+fm/0Z+yfETxHjw4rW4dp1ZoWAvi+J68B+mx" +
            "XL92+ro0GVaOkS65ANBqeyE7YfNcTbdSkbr0+J28Bat/fTysfaaEj3922dI3wspqW2L77iO6w9fx08ER" +
            "f2j8wTKtVv+3rA/1RlnefXgI0ODhMdz/RTt09R1nBp9aV0uO3z6IFMyvY82wdRJ/skb91EG5buoROPyA" +
            "aUD75mLwEaN1L++jzZv7Sf/KJ5fT0PbPp1JMrY2uX8rJiWrtqJk1Woy4u7Wrvo/UvdXCnOHvMO4A2b0/" +
            "Shn91soLOml5G61Znbji2kh/pYLa2bPh3F235f8+P9K35q8YrgIaGhunhDfzIqn5yqYJnFtXV8r/6/El" +
            "MNFvFEQFozqZhdQd74Jk97O0unzZn+11eAYQO8c629MFecLhkQhHdf/NJNGWSO/BEDQGI1qxsoNKSoih" +
            "rzOfuvX302nsHx+S7nOENQBhtPfnKflbLFTfUx9rnYY1TB+c1VNDya6eypz312v6MI0u2gjwf9Aagv39" +
            "wkA4l9KMuhJpeffHkPMuX+9dd//MpdPZP9U+gOw8NqohIf65C3gC08c1j0xPpmmyCunWtXubm3Fc6e1f" +
            "8ehoVF+tvZS+/nT6kNl1dced5AdDH25K0e6/+YdsVS4+jOSfG86xnPA2IRwxXXHCctij6QpvUaNOH5AV" +
            "Ab3ykv6QXqR/yjZdN8UHrH9h40+XHE2zXpVff9eMq5DxAGN7+77OETme6cEktnTS1THvc1QPTjy+l8xf" +
            "Vas37qClJeGzhenIeoK07e+hgt77z/Mulda5rrLXvqov0th9OHqVtzfHN4WmNTjngPEDo/+hSZXkxnf0" +
            "T/YhGV86VfIzGqir0TfDhVvfDPfTWO6Lyjt36Oa+fnVZDZaVMR8IRH3Rm4MHnOcyQ/vOv5Aqk0y7r/J1" +
            "tehEXFcAy47OYK2izZol11uLl4USnr0AJFa7R0TWolWHuDH+G7jonTmF86OgaoGSvvv+nqzOf+U4D1K5" +
            "WWXBpHiM+V86lY3PUMyEute7TP//iyuXrmNMAJZmAsQoVa1NT5bT5WbVhbdUEqq5UUfaalOw9tlBAczj" +
            "2bKdbIMGIV1vttOk5NWxNpd4X3MZdTnrLHbA6wdz/8cstlFTNAcT8iFzw373AmVGq4Cm0LhWRneH7X26" +
            "aTviXz2TLl3z44PQViO0bHHH70p5L4yUZXzgNcvkOW+c6DVBlmf4qw93ebIllq17Ol6pyvQa27MmlXqc" +
            "BmsTENSd6hgjzRb4n+ABfdGlijdt9PacBaqjnZ9m5GCFdg7iWn8mHhnr+OVHc/jgNECYauQD5pl3+LYN" +
            "JbXDOB/jOTbam1hXH304DBEGwmkGX3mt0f7ZaZ3uUz/nA+R6Vj/vTeYCWzNeHazR+0csG2sctbqbvxyI" +
            "B+KBLS+a7vye18wCduUAvIiL23v/U36sQbOeiDs9coP/x6KDLd77zAC2cXcn2A97xeI8dznb0feC768l" +
            "5gErUSs6LztDHDr//aYJ8iJtJBQE2w3Zdgs/w3fXkPEAQ8Bfn6ZfA4Baw7sV9rus8xj7YzN2+OJ/HVBZ" +
            "jhhcAnaE60tOmlGplQl8CL0nxJcFWru8GX+GzD8kLgLB+6jcZ1n49ttGf/XUy2QpfuTVjLoHlBUAQ7Fd" +
            "q9Sm3URP2Gsy0b5ALwsNGbl9E+AhffUneAITdvpZdzq9AffSFfcQtA4q7UWAbbOQSfISvviR/LFWKXnf" +
            "pZMK6cl1Cp/SO9a1qHb1+DyFdWdv5sAm2cR1n+AYffUpeATSyC8dv+WAvxBBjx3qXZuphC2zKFN+8Wvk" +
            "GH31KXgEEYZfMq6JrLuF/pa0d/fSH+5qduBLhyvN7ZQts4tK16soD33xL3gEEgW+7vp7mq92+uNSiGux" +
            "39zbH2idCnwc2ZIIHvvzxunrOHWePeQkQ9hm8T+2FmCmwHreMFWoz8jhGZ/hOfHem2xZ8gC/c3onO0qM" +
            "MKxpoXMaErrtsOhF27rj1oZYx78lIZ/VCtV/0cvUrt/3WZTwkxHMebqge2YfR1qOrGuj0U/y7dUU+eA0" +
            "QnPhga4L+/Fhr1tvjYk+eW66ZysYZReLk8om5LUxPcE+YR9eHzvKDy2fQeafXjM727v/eAwTFAVG6N/b" +
            "oWgP7E56/qGZkcyoANWmccceI5wEwmFXHxCg3RB9tC6482I7Yd3jgU0EABEdwO1u1pjXj+zNw7ugEmBb" +
            "PraSli2tp4ZwqmjmtjCZWpw9kx3AcMcwIQ0UkIYLBsoUm+k70eR66bYbXt63IF3wWDEBwpk1tRHCnenf" +
            "Yjhb9ljA4L1PCmvsatV69uuIYSFi3haU33OqJTHXiOEZb6DD7uCWfzr+CAghO4q03a1Un9oXv3lqoczz" +
            "f+XjOg6G6r6MtnV4FB1DkKF5c8tfn9tCX6k04cSZMT+AJs48PCbPRrWABgvN4TxfeWvjsPzup67B+o6p" +
            "shMr1HMyqY2IUc1u+TU/k4mtBAxQJgRe/vapeYvL8G520t5PftCoqM95PBINh32psfu7TrPp4/Q0CoEg" +
            "c7PaxeUeS8N6Ntzd3U88R/ZLiqEw2nwiARwwzwlARSehLMFg2vmU6JyiARouB12Y2qbcebtreQ1sUVHg" +
            "QiBedZJOwYhSL/rBmDcuOsHrChwD4bHzL9ZxgAUonFK5ImIQ9pN5j2tM39P0VCleYKrUnNTZ7wHp915c" +
            "bp/PNVp7TG0zZclpXL8CI6wW9Optcz/dyNt51UUOyTwAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgA" +
            "KqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+Co" +
            "AWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCo" +
            "FoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24K" +
            "vApAFUUOqUgAKqbUt+CoAWRA1pCoFoJBa24KvApAFUUOqUgAKqbUt+Potxx8cBjcuvCkAAAAASUVORK5" +
            "CYII=")]
        public string OnOffEnabled {
            get {
                return ((string)(this["OnOffEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAABGdBTUEAALG" +
            "PC/xhBQAAC1JJREFUeAHtnftvVMcVx49522AbiAA7fpUQMHYwpooN5hWVxpaCE4UkVKU/NCotjwbSpk1" +
            "bG2Obgh9Sk6qtgEhxCPAHpDVKIMRuw69xYhrJDwwBQiC2CQQEwYDBtnj2HqONtmZmdpbxrmeW70ho1+f" +
            "M7D3ns19m773zuFEpqWl3CQUEHpDAsAdsh2Yg0E8AAoIQjAhAQEb40BgCggaMCEBARvjQGAKCBowIQEB" +
            "G+NAYAoIGjAhAQEb40BgCggaMCEBARvjQGAKCBowIQEBG+NAYAoIGjAhAQEb40BgCggaMCEBARvjQGAK" +
            "CBowIQEBG+NAYAoIGjAhAQEb40BgCggaMCEBARvjQGAKCBowIQEBG+NAYAoIGjAhAQEb40BgCggaMCEB" +
            "ARvjQGAKCBowIQEBG+NAYAoIGjAhAQEb40BgCggaMCEBARvjQGAKCBowIQEBG+NAYAoIGjAiMMGodgY2" +
            "zZs2i1LRUYWadHZ3Udviw0PewGiGgAd/80/lP07OFhQOs9/78qK4OAhpABj9hA4Dgz+AIQEDB8ULtAQQ" +
            "goAFA8GdwBCCg4Hih9gACENAAIPgzOAIRJaCEhAT62YoVwRFAbSMCEXMZn56eTtVVlTR+/HiaOHEivV1" +
            "TYwQmVI0XL15EXZe66PCRI6E6RFg/NyJ6oAXz59M//v63fvEwvRdffIHWr1sXVpA6B3vqqcVUVlpKb7z" +
            "xF8rJydFpYn0d5wWU8+STVF5eRqNGjfo/2LaJiMVTunEjDR8+nEaPHk2VFVuIhe96cVpAmZmZtHnzn2n" +
            "kyJHC78EWEfmLxxcox1xWVkoZGRk+k5OvzgooMTGBqquraMyYMUrwzz33LM2YMV1ZJ5ROkXh8x+Nek3u" +
            "ihIQpPpNzr04KaMSIEVReVkax48YpgV+8eJFe/8Mf6csvTyjrhcrJAln3yiv9P1uyY/BJf2VFhbQXlbW" +
            "zxe6kgFavXuX1KjOUDNs7Omj9q7+h48ePK+uF0nnjxg3aULKRurq6lIeZOnUq/eqXK5V1bHU6J6Ds7Gx" +
            "a/tJLSp6dnZ1UVFQc8ItTfsggOftjKQ4cy/LlyykrK2uQjhq+j3FKQMOGDaNX16svzy9cuEBFxRvo8uX" +
            "L4aMY4Egd3jyiIk9EqpiioqLo9d//TvlzF+AwQ+J2SkA8T4e7e1m5efMmVVRW0aVLl2RVhszOIirZWEo" +
            "co6ykpKTQ0meekbmttDsjIL7aWrnyF0qINTXvDOk5jzI4z3ny5EnauWuXstrLL/884JWl8gPC7HRGQAX" +
            "5+RQXFyfFw1NNP9y/X+q3xfH++x9QU3OzNBwehilculTqt83hjID4pqCs3L59m7Zvf0vmts5e83YN3bl" +
            "zRxoX37typTghIB434vMDWamrr6f29naZ2zo732LgmGWFc50zJ1vmtsruhICWLPmRFNrdu3eptnaP1G+" +
            "r4733/kkcu6y4cjJtvYD48nbe3LkyztTQ0EBnz56V+m11nDt3jj5rbJSGl5ubS3zbwvZifYSZmRkUHx8" +
            "v5fifjz+W+mx37N//kTTE2NhYmjlzptRvi8N6AeXm5EpZ9fb2UlOT/IpG2tASR0tLC/X09Eijmev1QrY" +
            "X6wU0bdo0KcP/fv458XiTq4VvKjY1NUnDT09Xj/dJG4bRYb2AHntMfuf5iyNfhBFVaA7V7PVCspKWliZ" +
            "zWWO3WkBjx46lyZMnS2F95d3Zdb18fepraQqTJk2imJgYqd8Gh9UCSkxMVDI6deqU0u+Cs72jXRlmUtK" +
            "jSv9QO60WEPdAstLX10fXrl2TuZ2xd3dfU55IqxjYkKTdAlJ039evX7eB36DEoMolJkb+n2hQDm74IXY" +
            "LSNEDdUdA7+P77q4rLuXHKRj42g/lq9ULC/kutLQohgGkbTQcW7duI/4X1hKiXMKRg9U9UI93o1BWoqO" +
            "jZS7n7KpcVAxsSNRqAfUpBGT7yWUwX64ql17Fz1swxwhVXasFdLX7qjTvcd6SHh4vcr1wDpyLrKgYyNq" +
            "E0261gL755oyShWqOkLKhRc5AOZw5Y/dMA6sFxAON330nnyCf4cBodSCtqnLg3FWDrYE+Oxx+qwXEAHh" +
            "dlawsWOD+5gSqHFS5y5iE2269gA61HZIymeXt6ayaaC9taImDY+ccZKX1UKvMZY3degG1NMtHq3nGXt6" +
            "8edbADDYQjl0167C1BQIKlul99Y95a9tV5wELFy28r40rBlXsnDPnbnuxvge6desWfeLNe5YV/l+cJnk" +
            "0gayNDXaOWdV7cs6cu+3FegExwAMHDkg58k/AqlWrpH5bHRyz6udLlbNNOTkhoNbWQ3T+/Hkpt/l5ecQ" +
            "PSXGlcKwcs6xwrpyzC8UJAfH6qX/V1ip5rlmzWum3yRkoVs5VtWbMplycEBADq6//t3K/H95rMNC+QTa" +
            "A5xhV+yLyZlScqyvFGQHx6gtezakqa9eusXr7XF6izTGqCufo0koTZwTE0D/Yu5d4Xbms8ElpubfzaaD" +
            "xJVn7UNo5Jo5NdeLMuXGOLhWnBKSzCwdPjaiqrLBqpJ5H3Dkm1bQNFg3vMMI5ulScEhCDbWtro337PlQ" +
            "yTkpKou3btlrRE3HP89b2bcQxqcrevfv6c1PVsdHnnIAY4js7dtCJE18peSYnJ/d/cUP5SAE+to54OJc" +
            "d776rzMdW5/D4+PFbbA1OFhdvztTs7fKVX5BPowc84sC/De/T/OMlS6i3p5eOHj3q7wr5e77aKi76U/9" +
            "jDVQH48UBJSUldOXKFVU1a31RKalp8k1qrA37XmBPPJFJf33zzfuekyEKmwW0c+eukD80l28S8n0e1aW" +
            "6Lz6+2iresIGOOLxE22kB8ReRlzePtmzerL09Lu/Js3v3buJdUwez8NgWD0+o7jD7H49Plrd4O9Q3Nh7" +
            "0Nzv33nkBMXEW0abycq2eiOvzT2DjwYPU8ElD/+vVq/K511xfVng+Dw+I8qh6oKkZ/p/BPU9VdbXz4uG" +
            "cIkJAnAj/nFVVVQV8fgbX9S8spsPeDq+ffvoZHT12jE6fPk3d3d3+Vb5/z5fjfFXF01B5JiFPBlPd1/m" +
            "+od8bPufZtGmT0z9bfulEjoA4qUe9zRjKvZ5o+vTH/XMM+j2vueflxryBFRdet8X3cFSrJ3QOwldb1V7" +
            "Pc/bbb3WqO1EnYnogH21+Dtev166lZcue95mseOX7PHyprtqp3opAgwwi4gTky58fXPLaa7+lHwzxJk0" +
            "8PMF3mPkGaCSWiBUQf1n8eMkXli2jFSt+ShMmTAjr98ej6jwwymNbrg1PBAMqogXkA8E3FAsLl9JPvEc" +
            "qTZkyxWcOyStPBqvds4fq6uqdGlV/UBgPhYB8cHi3j+zs2VRQUECLFi4ctO3jeAI8z2Hmaag8k9CVyWA" +
            "+LiavD5WA/EHxYzNnes+an/PDOTQ7azalpqbSI49M9K8ifc8rRnnRH69Z42VHvHrChQnw0oQMHA+tgET" +
            "MeEPL5OQkiouNo+iYaIoec28Lmd6+3v7xNN7ogNfrq5YZiT43km0QUCR/u2HIzcnpHGHggkNoEoCANEG" +
            "hmpgABCTmAqsmAQhIExSqiQlAQGIusGoSgIA0QaGamAAEJOYCqyYBCEgTFKqJCUBAYi6wahKAgDRBoZq" +
            "YAAQk5gKrJgEISBMUqokJQEBiLrBqEoCANEGhmpgABCTmAqsmAQhIExSqiQlAQGIusGoSgIA0QaGamAA" +
            "EJOYCqyYBCEgTFKqJCUBAYi6wahKAgDRBoZqYAAQk5gKrJgEISBMUqokJQEBiLrBqEoCANEGhmpgABCT" +
            "mAqsmAQhIExSqiQlAQGIusGoSgIA0QaGamAAEJOYCqyYBCEgTFKqJCUBAYi6wahKAgDRBoZqYAAQk5gK" +
            "rJgEISBMUqokJQEBiLrBqEoCANEGhmpjA/wA6Xsalee3D6QAAAABJRU5ErkJggg==")]
        public string OnOffDisabled {
            get {
                return ((string)(this["OnOffDisabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAF+mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHV" +
            "ybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29" +
            "tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21" +
            "tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV" +
            "2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHh" +
            "tcDpDcmVhdGVEYXRlPSIyMDE5LTAxLTEzVDAxOjE4OjEwLTA4OjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjA" +
            "xOS0wMS0xM1QwMToxOTozMy0wODowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxOS0wMS0xM1QwMToxOTo" +
            "zMy0wODowMCIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3R" +
            "vc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLml" +
            "pZDo1Yjc3Mzk4Yy0xZjhhLTVjNDItOGMyNi04M2Y4NGYxYWQyM2MiIHhtcE1NOkRvY3VtZW50SUQ9ImF" +
            "kb2JlOmRvY2lkOnBob3Rvc2hvcDo0NzkwZmExNS1hY2YzLTUwNGItOTMyNC00ZmUwNTZkZDFjZWIiIHh" +
            "tcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo3NTc5MWVhNC1lYjFjLThmNDItOTg4YS0xMjR" +
            "kMDBkNzJiM2QiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJ" +
            "jcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjc1NzkxZWE0LWViMWMtOGY0Mi05ODhhLTE" +
            "yNGQwMGQ3MmIzZCIgc3RFdnQ6d2hlbj0iMjAxOS0wMS0xM1QwMToxODoxMC0wODowMCIgc3RFdnQ6c29" +
            "mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3R" +
            "FdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo1Yjc3Mzk4Yy0xZjhhLTV" +
            "jNDItOGMyNi04M2Y4NGYxYWQyM2MiIHN0RXZ0OndoZW49IjIwMTktMDEtMTNUMDE6MTk6MzMtMDg6MDA" +
            "iIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3R" +
            "FdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHR" +
            "pb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4xbACAAAADeElEQVR" +
            "4nO3d3XGcQBAA4cHlQJyIUlIwSsmJKBP8RJmi9AfNsjO7/b2LA7ZvQHcn3bKua0hX/eq9A6rNgIQYkBA" +
            "DEmJAQgxIiAEJMSAhBiTEgIQYkJDfvR54WZam2395fT/7I2ffFDx1AH/f/pzc/Dm93tPsFlAS5Kzvf7b" +
            "tsyGxmS9hdz5lp/1Iw4wTqNVib9udahrNNoGemBRTTaOZAnpyYaeJaJaAeizoFBHNEpAamSGgnpNg+Ck" +
            "0ekAZFjDDPjQzekBqzICEjBxQpktHpn251cgB6QEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBiQEAM" +
            "SYkBCDEiIAQkxICEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBi" +
            "QEAMSYkBCDEiIAQkxICHdvvLy5fX9zH9vL/81khe+RTri3H+473KOnEBCDEiIAQkxICEGJGTkgDL95pZ" +
            "pX25VJaBhv7DtCyWOuUpAlQ07fSL6BvTEiR168Xa6HWelCXR1pPeM6Opjl7h8RdQKSAlVC6jSFHpq+nS" +
            "9TPcO6MmDH/Wxuuod0BXk/iD7jXuZe59NhoCefrYujR6z1Xa/e8yuMgR0xR3P1DtP/h3bKjd9Ijp+oOx" +
            "gifMncA2+cPuf73nzeiWe7tMnIk9AGaRYkGoyXcKuLGDJsX9QdvpE5AroqsoRVd73iMgX0PAv/e9UelH" +
            "0U9kCIipFVGlfv5QxIPpCXObFofuXavpE5Awogp+ojBHRfUoXT0TegCLuiShDSHfsR8p4InIHFFH/Fd5" +
            "sr5jfbpYXEvcL2XpBMky9x2SfQBH3L3irS1uL7aaePhF1JtCV98q+c9ze2cVqPWnSxxNRJ6CI/ye01cJ" +
            "lufSUCGdT4RJ2VOoEn1Tu2CoGFFHwRP9AyWOqGlBE0RP+ibLHUuke6COt74taKxvOpnpAm2ohlQ9nU/k" +
            "S9pEKC1NhH39slAm0l3UaDRXOZsSANuQD8y32YUgjB7T3ZEzDR7M3S0B7xwUe9qMWT5gxoKOr90xTh7M" +
            "Z7bcwPcyAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhCzrmu2vX1SJE0i" +
            "IAQkxICEGJMSAhBiQEAMSYkBCDEiIAQkxICEGJMSAhBiQEAMSYkBCDEjIP0rEWVN4W4JCAAAAAElFTkS" +
            "uQmCC")]
        public string Mic2Enabled {
            get {
                return ((string)(this["Mic2Enabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAQAAABNTyozAAAAIGNIUk0AAHo" +
            "mAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwA" +
            "ACxMBAJqcGAAABuBJREFUeNrt3WtsFEUAwPF/W0RBwWqE4AtEilAQidBisQ2JhLYU/IAxIkRiwIAoFj6" +
            "pIRg/EE0Mxg8SQEWs0QQRJFGDiraHL1rQ9lpUQItiY6xvxSBCIq+2fgCCcrOzj5ndndubuW+zs3tzv9v" +
            "d2XnsTN5D2CAL+ZbAAlkgC2SBLJAFskAWyAYLZIH0h15G5KKIasopZjD9gMN00k4T9XTEn7W8mCurBcx" +
            "iMTc5bP2E1WyiK3cvsRraWe/IAxN5hS+pyk2gvrzIVoa7phtBPevok2tAA2linufU82lkQC4BDaSRG33" +
            "tMT4uIv9AhTRQonhxvcd1vvcawVYuMB+okBSVpBiv8J2rfJ49Z0IJT5sOVEiKEqCQbYGJargncG4XMsV" +
            "koDM8KBAVsFIpv6uivmvmB+IJTjTLQ8EuCyOZaSbQuTxBiWqVc1xrIpCIJwhREWXKOS5nqHlAmx0Ldn9" +
            "E1VryXG0e0DL+kpxd3okqtOS5wjygNFVaiIq15LnYPCBdRFdryfNgM4t5HUT9tOS5v6kPiupE52nJc29" +
            "zqxqqROvIuuD3wV2NaGH2Efmv2agQ9WQfUZCqX5oqDuUKUbC6cZpKJaLnkw6kSnRf9hAFb13JESKV5qe" +
            "cIFJrn8sBItUGTFWitUkHUiW633QiHU3giSbS00eQYCJdnShuT9cpF6Lnkg4ELVKiS1yIFplKpLMbLpF" +
            "EevspE0ikuyM3cUT6e7pViZ5NOpAq0QNmEYUzViJBRGENJkkMUXijbVqoViJ6JulA0KxEVGsGUbjjtRJ" +
            "AFPaAtqwnCn/EX5YTRTEksjmbb9fRjBlVISJeoqgG1WYtUXSjjpuplrz5ZSxRlMOymzkq2epOtCbpQG7" +
            "Bjag2DiKzXuo1kMi0t56NI1IDOsbJjE+pJP1xLURPSLaW0pPx6YoPqJuCjI9sDOphLWfRMsk20butR+M" +
            "DEv1g2VDfH3xcaOMCXqJB/5ZQgP4UxF0mSd/u44duC0R0uSDuj/iAfhLEjZSkb/J1LgQhEr0J9GN8QN8" +
            "J4kZJ0qfoDplotMdcRgT0lSBujCT9z3zk847il2icx1xGBPSFIO4q6Svfq33fdP0QDRPegz6PDygtvGR" +
            "kc228ye4QiUSv2p2gLc5iXnQO1Uj26GFJgKLbK9EMQVwr/8RZ1UgJ/8crJHt87Psy80o0iMmC2IZ462J" +
            "vC+IKmCvd50GaQyGaR4Egdku8QDv4VRB7r/TNsGPc6uOR0TvRpYK4DnbFC9TNBkHsEJfpJw4wibR2ooc" +
            "Fr8msj7+54wVh7KMuM7UcYFKAYeRyosw3ibqoix+onQ8EsVey1GW/oyykiq9DJXrLc/U4RCB4yqFRYoy" +
            "HMnA0c3zesv0QPan+4/TMgtcqbL9p42ZPTWSnpgmsoJgh9COfQ3TSznQuckx/kCmSm28ea1kAvK9jMh0" +
            "9QFXUO9yfFvjPET0AVPCuIlFZgMeJzGeWch1AHZRRJKw6HghQWp0KnTQy0/EV8D7MJMUvkuezfQ5/Wix" +
            "nEAxnD+cL4ru4i02Bj6pyFmkKuno19vOY+AzlFe4IfNQmpnJEa3tRbECwwuFiKmADixSe1KdK2pQjINI" +
            "HdJLZ/C3c0os1rAk8re4OauIk0tlx2MHc0yVQZlhEY4C5Ew0g0tuz+gbLHbeV8RlLhPVtoy803V3Py3n" +
            "JcVtfVrKbaYGOuzMuIv198/N5XbJ1FO+wnRkBvvdTVim2F8X6HPTf0JuN3OZ6v6rjNc8zjl/LHOZxjUu" +
            "qUJ6LwpmRvBd13O0h3S7qaWSHQ+kH/ZnAZKYx1uP3hkAU3pTtj/OIx5TdfM+37Od3jnCYk/ShkEEMpZi" +
            "h5Pn8Vu1EYc5pfyd1XEjUQTNRmAOoNlHiuxdMPWi+XYc7wmwfpayIfFUDrURhD8E7zlIm0BrKsU9EQRT" +
            "FGMVdTGCu2iCUjLCX6ZRL5lLTRhTNIM4eXqaIxXRqOdoeZjOWrS7TzWkiim6U6zFWM4zZbFc4RhdbqOI" +
            "GNp4eNBEBURxL1wxnDrcLhzrJzsFmNvOqoJG1lAYKwyv041vbZxiV3MJElwlwe/iGnXxIA785pgmVKC/" +
            "2lXoHcL2w6xGgnL2O1ZCIiPKMWMrYqZnNe0WjlBQXh0GUlAXY5FM8Kdyuk7NCXUhESVrCLxSiZK1xGAJ" +
            "R0haB1E6UvFUyNRMlcRnRtMvMM76IkrnOaos+oqQuRKuNKLkr9WoiSvJSxm5EK3IdSE7U5m0pt6Qvhu0" +
            "0UVgblRy0QCCeVqWVKd54cmM59XOJ0lRKGmpzEOj/RL54cgXoLFGLtCKSw0CniBqkBb8wmNHkanDItwQ" +
            "WyAJZIAtkgSyQBbJANlggC2SBLJAFskAWyALZcDb8C7SDM8ogjdusAAAAAElFTkSuQmCC")]
        public string Mic2Mute {
            get {
                return ((string)(this["Mic2Mute"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAYAAADnRuK4AAAACXBIWXMAAAs" +
            "TAAALEwEAmpwYAAAMsGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78" +
            "iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTp" +
            "uczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA" +
            "4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3J" +
            "nLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB" +
            "4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8" +
            "vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS9" +
            "4YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bWxuczpzdFJlZj0iaHR0cDovL25zLmFkb2JlLmN" +
            "vbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlUmVmIyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9" +
            "lbGVtZW50cy8xLjEvIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9" +
            "wLzEuMC8iIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIiB" +
            "4bXA6Q3JlYXRlRGF0ZT0iMjAxOS0wMS0xM1QwMTozNjo1My0wODowMCIgeG1wOk1ldGFkYXRhRGF0ZT0" +
            "iMjAxOS0wMS0xNlQyMTozNjozMi0wODowMCIgeG1wOk1vZGlmeURhdGU9IjIwMTktMDEtMTZUMjE6MzY" +
            "6MzItMDg6MDAiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6ZDIzNjQ5OGUtNDRlZS04NzQwLWFiMjg" +
            "tNDQwYzNiNDk5NWYxIiB4bXBNTTpEb2N1bWVudElEPSJhZG9iZTpkb2NpZDpwaG90b3Nob3A6OTVhNDU" +
            "0YzEtOTcyNi00YzQzLThjMWYtNDNiMzBjYzMwNWZlIiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9Inh" +
            "tcC5kaWQ6OGM3YWIxYmItN2ViYS1iZjQ4LWFhOTgtM2E2M2E0N2E0MzlkIiBkYzpmb3JtYXQ9ImltYWd" +
            "lL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUV" +
            "DNjE5NjYtMi4xIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0" +
            "iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo4YzdhYjFiYi03ZWJhLWJmNDgtYWE5OC0" +
            "zYTYzYTQ3YTQzOWQiIHN0RXZ0OndoZW49IjIwMTktMDEtMTNUMDE6MzY6NTMtMDg6MDAiIHN0RXZ0OnN" +
            "vZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIvPiA8cmRmOmxpIHN" +
            "0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6ZGQyZGIzMTItMzYxZS1" +
            "lMTRhLTgyZDMtZDk2ZDMyZDM0OTIxIiBzdEV2dDp3aGVuPSIyMDE5LTAxLTEzVDAxOjM2OjUzLTA4OjA" +
            "wIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHN" +
            "0RXZ0OmNoYW5nZWQ9Ii8iLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5" +
            "jZUlEPSJ4bXAuaWlkOmYzZGJiODViLWZlZTctMTY0Zi1iZGQ4LWQ5YjMxZTAxY2JkZCIgc3RFdnQ6d2h" +
            "lbj0iMjAxOS0wMS0xNlQyMTozMzo1OC0wODowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGh" +
            "vdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDxyZGY6bGkgc3RFdnQ" +
            "6YWN0aW9uPSJjb252ZXJ0ZWQiIHN0RXZ0OnBhcmFtZXRlcnM9ImZyb20gaW1hZ2UvcG5nIHRvIGFwcGx" +
            "pY2F0aW9uL3ZuZC5hZG9iZS5waG90b3Nob3AiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImRlcml2ZWQ" +
            "iIHN0RXZ0OnBhcmFtZXRlcnM9ImNvbnZlcnRlZCBmcm9tIGltYWdlL3BuZyB0byBhcHBsaWNhdGlvbi9" +
            "2bmQuYWRvYmUucGhvdG9zaG9wIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5" +
            "zdGFuY2VJRD0ieG1wLmlpZDowM2FlYThhOC1jODMwLTY4NDUtYWI3Yy01MWI0NDc2NGExN2QiIHN0RXZ" +
            "0OndoZW49IjIwMTktMDEtMTZUMjE6MzM6NTgtMDg6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2J" +
            "lIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8cmRmOmxpIHN" +
            "0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6M2E4MzAzZDQtNzIwNi0" +
            "yMDRkLThlZjktN2NlY2ZlMzI4YzAzIiBzdEV2dDp3aGVuPSIyMDE5LTAxLTE2VDIxOjM2OjMyLTA4OjA" +
            "wIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHN" +
            "0RXZ0OmNoYW5nZWQ9Ii8iLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249ImNvbnZlcnRlZCIgc3RFdnQ6cGF" +
            "yYW1ldGVycz0iZnJvbSBhcHBsaWNhdGlvbi92bmQuYWRvYmUucGhvdG9zaG9wIHRvIGltYWdlL3BuZyI" +
            "vPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iZGVyaXZlZCIgc3RFdnQ6cGFyYW1ldGVycz0iY29udmVydGV" +
            "kIGZyb20gYXBwbGljYXRpb24vdm5kLmFkb2JlLnBob3Rvc2hvcCB0byBpbWFnZS9wbmciLz4gPHJkZjp" +
            "saSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmQyMzY0OThlLTQ" +
            "0ZWUtODc0MC1hYjI4LTQ0MGMzYjQ5OTVmMSIgc3RFdnQ6d2hlbj0iMjAxOS0wMS0xNlQyMTozNjozMi0" +
            "wODowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3M" +
            "pIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8eG1wTU06RGV" +
            "yaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDozYTgzMDNkNC03MjA2LTIwNGQtOGVmOS0" +
            "3Y2VjZmUzMjhjMDMiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6MDNhZWE4YTgtYzgzMC02ODQ1LWF" +
            "iN2MtNTFiNDQ3NjRhMTdkIiBzdFJlZjpvcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6OGM3YWIxYmI" +
            "tN2ViYS1iZjQ4LWFhOTgtM2E2M2E0N2E0MzlkIi8+IDxwaG90b3Nob3A6VGV4dExheWVycz4gPHJkZjp" +
            "CYWc+IDxyZGY6bGkgcGhvdG9zaG9wOkxheWVyTmFtZT0iVm9pY2VNZWV0ZXIgTm90ICBSdW5uaW5nIiB" +
            "waG90b3Nob3A6TGF5ZXJUZXh0PSJWb2ljZU1lZXRlciBOb3QgIFJ1bm5pbmciLz4gPC9yZGY6QmFnPiA" +
            "8L3Bob3Rvc2hvcDpUZXh0TGF5ZXJzPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1" +
            "wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PvvuGj8AADgJSURBVHic7b1pdGXXdd/52+fe+2Y8zEOhJlY" +
            "VpxJF0hSpMVIk25JashQpdkzZsexYtlfTcTwkvdK95G53r6x8aDe9VjqdrCROe9IQSW5bk1uSNdiSnJA" +
            "SbUkkTUuiSInFQs2F8QF487vTOf3h3Ac8oICqh4eHKhS7/rVuAbj33DPuu88+e++zjxhj6AfqIl2nFaA" +
            "KzANjgA+o5F42ea6BEEgDQce7MWCS9CS/O4AHRMnfcZJH+7kB3OReDKMajrlwp4LbIzii4ZDAsEARyCf" +
            "ZuUkWUVKVuoGKgRUFF104H8GLEbzgwBkHSu16d/aoScqVpC1+kqZdP+lIo5K666RNbnJPAfWkUl7yvAF" +
            "MAoVN5V0LhT6NdxvutZPc9BgEXgW8zsCDwEkFYzF4MTgCStkxko4LNtIggJHkAnRoxzF2LXEtGXhe4Gn" +
            "gr4FvAeXr1L4bipcqAR0F3gL8iMBDAiMxpMUyAQ/WqaMLbCaoK/+AIQNHI/hhsUymhCWmvwL+EjjfUyt" +
            "uArxkCEjs1PNO4N0Cr8FORwNAKnm+1/DEEmcBGAVuA94q8D8D3wA+I/B57Gz0ksFLgYCOavi5AN5u4Ki" +
            "xosF+aFcKS0ijwBEDf9+Hf67hCwIf4SXClfZDR/cEA7cLvE/gvwNu1zB0o+t0FbjAoURYfxnwD4EvAR8" +
            "GXryRFdstbjoCMnBA4BfETlf3A7kbXacdYgh4CEtIPwp8FvgQMHfjqtQ7biYCcoH3CLxX4I1YmedmRg5" +
            "4rYF7gdcDfwx8HKs2uGmw7wkoWVc/EMM/EUtA0ze6Tn1GAXiHgR8y8ErgvwDP3OA6dY19TUAC6Qj+oYF" +
            "fNfCGG12fPcZBDf8Cq6v6j8BnsCqBfY19S0ACtxl4Xwi/Doxch2U4sK4VvoF4g7Ly0cuADwLnbmx1ro5" +
            "9SUDGTln/o4Gf2eOiGkBZrNa4YaDpQKjXzRdtK4iHXZbngLxY7faggcwe1WvUwL/SdqX5f8o+ntL2GwE" +
            "pDW+I4d/G8Ip+cIJNHKViYBFrtzpr4JSCsw6c1zBvoJSCestOHbFJTG0K0sbKKhMGphQcAY5ruAM4KjA" +
            "CjNPnFWEE7wXuFviXwNew5pN9BdlHxtRMFd4O/K6Cqb5UClCug5Ny8XIpMoM5MkN50sUsjtefbyfyQ1r" +
            "lBq3VOn65SdgK0EGEjvs31gbmDPwzD77oQWs/GVP3CwHlgZ+owx+qxPSwG4gIynPwcmkGxgbIjhdJDWR" +
            "3m+21YaC5UqO+WKFRqhL7IXEU72yEt8/ad+C/T8GnNdT3CwHthymsoOGnWvAHapfyq4igXIfMcJ7i9DC" +
            "58SKyA8LeNQSyIwWyIwV0GNNYKFOZXaFVbaIjDbsYPIF0DB/W9gP7E/aJTe1Gc6D0CDxcg490+vDsGAL" +
            "KcciOFBg6MkZ2pNBrTnuC2kKZ8vkl/HIDrXXPHKntB+XCzzbhk5Pg32gOdMMIqAZyEd6dho8nVuzeIEJ" +
            "mIMPo8Qny48Wes9lzGKjNr1I6s0ir1toVq9UQxPCeA/DZ/A752ktmChN4owO/1yvxGKyAPH50lMHDoyh" +
            "H7WqKuB4YmCiSG85TvrDM8oUl4qg3QVtBStu+WwUe62sld4i+caBGlxzIAapw3xx8WMEP9VKWAfLFLBM" +
            "nxskMpJG246oIiEp8DBOnV63B6OSnQZLmGiFJn/gkilr/2xibXsf2J+00HT9hPV07/wRtN9UNdel4x0Q" +
            "RfrXF4pkStZVGL11gmwbPTMHPF+C73ZJibr9yoG66IQB8OKzhtwzc12tZg9NDTB4bx3OBoAVhYAfTccD" +
            "1MKk0qDYhREgYQBRCFK8NtLQH1nXtO65n308GWuIQ/BaEob3neuClwHUxjgMIGI1EIUSBrUOb2ETsFOW" +
            "69h0vBY6LMQbiCBUFpCVAmbjXLgDAwP0V+K0K/E8RXOjmE75jVyVeib4R0LW+gMThPN2CX9TwD5x1v/i" +
            "uIUoYPTbG8MEh3JSLUQqyWfsTsZyozTW0tgPvpTHpJI1quz632ZDlINLmIsZAHIMIJp3B5ArrnCNJI7q" +
            "9mrIEa1wPVMHmv5kLJ1xs7R0BvBSRuMydrVCr7c7w7oBqwbsSf+xHuQG2s74RkHOVZxpLLQbepeHXsJs" +
            "vuoYGvJTH+F1TFMeyiAmJMJjBSZg8AuPTkMpA2ERK86hLZ1FLC2DADAwTT04TT0wTj46hCwUEjTTrqHI" +
            "FVVrEnZ9DlZeRWhUTh+hsFj1+gPjQMczIqOUwqyXU0gLOyjKqWkGiAJNKY0bHMQeOEk8eQg8U0ApMHCE" +
            "tH1leQl0+izN/EdWoIV6aKDfE/Jk5anMVTLw7DoTt0yy2T78n8MldZ7hD9I2Alra5r7FaQgP31eFfiNU" +
            "ddg0NZIsDjLzyZQwMuVBZQjdaxE4GPTSCufuHMHc9ALkCUllEvfg9vGoZlhYxykEPTRAdv4fgjnsIbzu" +
            "OHhtDTIQqL6MW5nHPzIB6Fi+MkUoN0wrQqQzR6BThfa8mPn4H+HXk7CmcF75HquUjlSpGG8jkiA8cQb/" +
            "sIcKTDxCPjxCLRkc+Umuizp/FdV28+ipuo4IONQvPXaJ2bg7TJ011wk/HFPwPCl7Q8J3ruZTYcxlIA2n" +
            "IaWtZf/VOllwG8EbHKL73p8mMZjAzzyGri4gfIm4akx0gOngMfdfLwXFxzseQyaIzOWRwBD0wTHj3fUR" +
            "3P0B88DBmeAyyBYyO0Ag6ncdk8nbKUgovipD5ANEak8kSHTxKeOe9SL2K0/JRc7MYL41OpTFDw+hjdxC" +
            "ffAB9+z1E00fQWRfdqmFcF5Mfw3gFK3uZmEilWP3m96leWOr7ajEholdjXXx/y0CzrwVcBX0joKsJNAG" +
            "8S+Afu1ef6a6A5HLkf/3XcV73GuLvP4Py0riRQfkaXEHHgnEUsaOR5gpq7jyyNIvoGDM6TnT4DsKT9xM" +
            "dug1Hh7jnTiNhgIkidNojHhsjnhiH6HZMFECzjtcoo/wGTtBCwsiaVCODExmcGIg1JpMhOnyc+L5XER+" +
            "7GzNQxJQXUecWcEqz4GVg+nZMYQRz7B6CWoPaF75O4/zi7jr5KjDgRPCPBb4J/OmeFbQJ14OADoXwPge" +
            "mdqo8y77nYbx3v5soClAjYzjZPOAgKo3yCoiXw3geOvZRSxdRp7+HungGg6AP3UZ098sJ7zyJSefwZp4" +
            "n9fx3cBbm0JEmmpiAe+9H336C+PARjDaI38IpL+DOnUeCFuI3kVYL1WzhtEJUpBEEnS8QHz1BeM8D6PE" +
            "DyEoJdfYF3Befxbl0FskVMSd94tvvxW/6VD71OVrPPLub7u0Kxhqh36fgCQMX97xArgMBKfg5gdd2rH2" +
            "uCQ0UXnEfA297K7HjYPJF4tFR4lwO7XqobB4zNIIZGsXkhzBOCqlWcWYvoJbn0ROHiQ8cITp4CFPMIY0" +
            "6snQJNfN9nIvnLMtvHcGMj2DGx4iHx9BTh4grFaLzP0BW5tHEYCJER6g4RoyAcjDpFNoFPTRIPDwMnoc" +
            "qr+KeP4N7dgZZuIRkC5jcIGGlTPXP/pzWV7/ac7/upN+S9K8z8F4Dv9NzoTvAXmuibxP4caC4k04YGCk" +
            "y+tpXoEMfooA4U8AMFDDZDDqbIXZTmIlJ9MgYJpuHEFS5irO8iKpViQ9niEYn0AMFRDdR5Vlk4SJm7iJ" +
            "m/gLiKVTWxZ29AKOTkCqgswXM2CTx8CiSSaMF0FZnI3Fol/mOwqRTGBdMysGYGFWv4CzM4l66iFNaxjR" +
            "bEMcEz3+b1Wc/Q/M73++p40QJhZECRhuqy7WuTB8JsRWBf4Q1uO65N+OOdTHbwWy6AAQeAU7uJB9xFRP" +
            "3HCalA5zlBVSzBq4DhQJmYABdHCQ6cJDw6DHiyQPguKjqKk5pAbWyAn6ATuWIBkfRhSJGCdKqQWUZWV5" +
            "ESot2yimXUKVFVKmE+AGks5ihEXRhEJ3KYJRjW6Jj0BGaGK3EKgXTOUjnrawTaVRlFWdpDrW6hGrUief" +
            "mKT/+JPXdEM9tBxh/zcsZufswnrsj0RFsnz9yPfwQ+kZA3qYr2T3xNqzLSteYPDRIeiQPrSo0ytCqI1E" +
            "EyoF0GgYG0GPjhBMHiIuDGB2gKouoahmJDag0OCmMctHKReOgjQNGIUYhKETs3yaK0UEAgQ9xZE0dohB" +
            "xQZLYGAJaYjQRWgyIg5I0qKwtSxz7XhygTETc9FmeWaB6sdRTP4rnknntKxn8p4/APffjHZ5mdHpopwb" +
            "8ArbvpzePS7/RNwIqdlyDgAe/YODYTvJID6QZPjICUYjUy0h5EWqrdoCVA4nsE08dJJo+TDwwgPg13Pk" +
            "LOKuLiAbjZTFO0lVaQDtgPEQ8xPEQNwVOQmTiYIzBxJE1RUQhxAbBSYjISTiqRkuEEQ2ibF7iIWsBWAy" +
            "IJmi1KJ1bojJf7akPJZ0i/ZYfpfiv/xXy8vsx45OYTJbCoSHS2Z0Nv4FjDvzCIDZAQPvqN/pGQPHGK6v" +
            "hHexgu7FyFJPHxxDXhSBArSyjFheRWgUAk8lBdgByg5ihcfToJCaXRzXquAuzOMslJIrBTWG8NMZxERy" +
            "cSOGGoGKNSAwSIxi730wEUQIKjJjkSgyy0jZ7ABj7T8AosXY2MbalOkRCn3ClzNKpecqzvUV1kZRH9tU" +
            "PMfquN5O5PIN79geopTmU38JJeYwcHbEeB91jGHhHBNkIu0tgL3Ys9k2I7gwCpeFdsQ2x0hVEhNxwjvx" +
            "YASOChCHS9HFWV1H1hhVgUxlMKgfpIiY3CPkBBI1qNHCWSzjVKqJjaxBVyg59DE6iIBFjMEpjlLYEJIJ" +
            "4HpLJQMrDiDW8YtohrDod3MT+MwbEYCQCAoz2kdgnWi5R/c4M1V6Jx3Up3H2CsTvG8R7/fOJd4EDLx7R" +
            "8xPEYOjBCea5Cs9zsalkmQARHV+EfaLvjFYBDPdVwe+zFKkw0/ITARLcvKE8xenQ0MUYKxDHit1DVKmp" +
            "5CVUqYUbGMfkieuoQeuogpjiI1FZR9SqqtISqrNopSDTEPgRNJI6snOKmMa6HcQQtBhErEJtsFgqDkM6" +
            "CNtBqrlvg4/hKjXFi3UeHEAegA+LFBeqf/yr1sz1ubVeK/H0vY+r2SbwzP4DFS/Z+toD2MpDKgeOBaxg" +
            "5MsLcc3PWz7o7TGDH4hP0xTN7i+r3K6P6+jUdwoOmS+IUEXLFLLnhDFaWwF6OADFOpYwzP4dUK5hcnuj" +
            "QIfTkBGTTQAyhD34TghaiAyT2kaCG+HUMMXEmTZTJoh0XE8UYv0Xs14hjH+2lMfkhJF1EjGNNJK2WVSJ" +
            "GgeV87SkNrLAcxZYwjSFeKlH/9/+J+jf/tud+y/7IDzP2th/GdRX4IbQCaAXoIMCEEcQaSbqlODFAKr+" +
            "jPQcu8JCCA+1Qef1G3zhQW8SL4e2yE9nHUwxOD238PpSCdAqUoFaXcc/OQMoaT/X4BPHoGMZRSNCEVsN" +
            "yjqBlfX+iFqpSQpVm0VMHiXMDUMiiBkdwhiegWkY7oIeH0cNj6IFhu7KqllFLizirK6hWy1rKTWLwTBz" +
            "NRGskCFDGYOYXaHz0z/C/8Bc927bSP/5uBn/2Z3AuzhCvLiH1GmDlMJPJgEn8ikxoXUJEKE4PETYCorB" +
            "rLjSk4e0a/qinSl4DfZ/CBN6KXYx1V4FsisJoIXGxSTwCcTCOZzcFrpZwLs6gR0bR41PEE4eIhweRRsW" +
            "u1mpVpFxGWi37iUURanEe59wMemwSMzyMGR5A33E3cauJOXonWhn05DTx3feiJyeQoIUzfxHn7Is4C7N" +
            "IENppw0tj0hkIfYxnv3zxA8xqhfI3/oTg2e/bqa4HpN/xdnL/y/+KZDLEIlb9PjgMq0fA86zTWnkJVbq" +
            "EVFYQI4iTYXBqiJXzy9A9AQ1gx2R/E1DyrQ5h3VSvueY0gOsqhscKluMkBGSMFSFxPLQRqFdwlmaJV5a" +
            "QWGPSOascNMZON/UaUqtBEGKyVrHnLJVwvbOYqQNwaApz8DbMsRPo7CCm6WOUQRdyxIcPo/NZnHOXUZd" +
            "n8M6dwl1aRCKNOCmMm3gSep5VZhqDrtYpPfk8jbkSpntZZAOyr/ohsv/0l5ETd6PrDeLDoXVeOzCNNKr" +
            "WQ0BHyLnvYcISqtxAtINyMijHIT9cIGqF3W5eTAk8kMwKqz1V+CroGwEla5dXuXab7zUhgPIccuNWO2H" +
            "aAjTWs8+IAjSqUQUd4cyeI549jzM8bqek5cuoy+dRy0tIs2mnEeVAHNuVmVzCnPkBjBSIjUG8ImZgEIp" +
            "eMuXE1ka2Ood68Vmc08/jXDqHqlYwbsZyspUSau4i+HXU6gqUSiw99Ty1y0sY3Zs/T+HOQxTe9GpIuej" +
            "5WUQbjI4xmSwMDaPzOcgWkNCHUhFSKatCaE+TxjrnV5cqO9n9OqLglQJf7qnSV0FfPRI9+HvhDgIOpHN" +
            "pvELK6l8AUJZVAyKJGSEOwNeoxUu4Lz4LoY+T8aBawjkzg5SXAWP9jwUEDcqgwhZq9iLud1ykVIbBcSS" +
            "VBzeLRBrHbyK6hamXcC6eRV2+AK0mRhyrLKzXUBdmcE2AxAHMnGLl849Rv7Roncl6wMDhcUbuOIzSMfH" +
            "ZU2i/hSCoVhOiABO1rEY8k7WKzUoFCQRFHsFgkiDDmcEcXiZF1Aq7LTqTjM3+JaDEkPcgNpRuN6jkBrN" +
            "FEbE6GABlOhZiBoxONMUxankR99R3kaVZjKswQQNnZRVVWQElVkYR+57xXETAWS6h6k3UpTnM8DDkB8B" +
            "NI4FGGg1Mswp1qwoQ37dlpa15Qmpl3LMvoFbn0Y0my1/6GvUXz9PrLpbi5BDjU4N4cYRemEMpwSzP2fa" +
            "GAcbEmDjGGI3xPCSOkdIiqhkhKmf1Uwbby46QGszSqja79WxMx/DQXqzj+0ZABkYia8TrKk8Di+mhbFG" +
            "M2aigkHas97YDO5jIINUaKrqIrJQwid+x8kNU4Fuu4ygMYhXEAqLtVGZqDeuCWl6BXM7uroi0lZ8adWg" +
            "2En1RIsA7glEgfg1n/gLMnqf0d2eonZvvuW+KE0UmDhbxUmDCFrK6hBM1YemyrazWicnE/kNZeYtGHfw" +
            "6Ruk14mkrNAtDORrzZcLuCMjVcLe24sVyzw3ZKuN+ZRRb28tot+kNLGYH0icwWF8bLCdqa4rtEjrRyKI" +
            "gFsQPIdaWQIxB4hgVR4joRG3cNlIkfzrW9CAC0mwiQWC5FXptN4Y4bqLnSYZQGVAGMT5xucXS9+eoXl7" +
            "puV8GpoYYPz6Ol3YSU0iMCRtQDaCRGHiNSQhEWwLCwRhBGx+tGxgnsmYZnbLc2WhyxRSe5xC0wq5cPQy" +
            "MBTZ29f4koDTcFe3A4KvgnHLVawAwiYrLKj2Sf9Z8gFLWIKqBILSGVSGxqltOZbNQGNPe3mPzWdNsm4T" +
            "jaG05nMJynPaJFB0EhGPNFVHDZ/GFhZ4NowDFySLjx8bxsh5GJR8IZl35acxa2yUhIPvxKDQKcWLwwuQ" +
            "jaC8yLNyUg5txbZCB7uDm4S6gd63nVpn2MaPboy6VnYnT92kjdtoxa1KPYS2LtuHSrD9ri0prJk4RNE7" +
            "yVNmkCQFZmUzsvbZ+acMgtMnMJKs+ICHKsBlQOtW7VR1gYHKQsROTqIyLTso2yAalo6DRInbhIO22m6S" +
            "9WFnMJM9xkYTQDdYA7OZSiI2kds0PV6xR5/aeG7QN+kZATTgiXRKQ2BNvzmhJdnhKxxMjycAn98UknQu" +
            "mfXaNrE9VmOSr7oDlJQmxJPkYdfW98201QtQIKb24QGWuN8MoIgxMDTF21zQq5dq6rU1RSRtF2ek1Kde" +
            "0yb29YbGD0ygMaBDTbrde8xhwcymwU9JkFzVzWjswcHeLfioSD3Wz2zSRaippOO+5KXtnTd6BNhElgs7" +
            "atGbvdz5fT76WZi0L6XiQpJWOsCpa1tO1pW4MQSNg+fQclbneZB5RQnFqiKmTB3E8Z00us1J/u/BOIpZ" +
            "Ndd3k12lIpri2C0lHg0VI59MAFbogIAPK7b8xvq9O9SN0fjpXRyOGeRyP9RPAdEIYau1PYE23CKw/j9t" +
            "TQUJgqqPDocMAqtaXvir5qRMCNGpD3kGtyeKLc5RneyUeRfHAEFMnp3FSiTss2ALaxlh00s52W6SjrtK" +
            "Rpt0fZr3+ohK5rU3wCi+bAah1VT+Q2PoI9RX91AMV6IKABNDQbMHyUsMHYowJMcSJjGB5u2grHaGSlVF" +
            "bVjIKiQW0sexdGURpBJ30t6BFWYUgytIWBqOSo9y0ILGyBJQ4k8VNn8bZBVoLld7argRvfADntnGWwwg" +
            "VBrQJyOBgsAQlaITY1rP9MWxBQLKJgAyCViqJAcDaVKfDGIFml/odMTuwUXaLfhpTuyIgAAOBgepnLy9" +
            "gOyq2S2s6OJBJCEhIFI0drD75SBUmkY91oqltC87rgyJtAmqv2Iwgev3rz0Qxh0o1xiqtnhqtRVgupJk" +
            "ZSBEvrVj1wto0BLaW66u8NqFvaM+GoAwdU93atGfbZNqRQxJu62nDa8EP6KrjhT04HqKfBNT1El4gcsD" +
            "/3NJGQdWs/bepQ2Tj8607a6Ns0SFRbfylI/9BbXhrI2DM783ZMwaeTTn8uauorzbWVokb69PtrH51rNF" +
            "cR9aegVdCuIMS+u5X308Cah9L2g0iQH/PHUz+3OK1TZ218dnGlcoVY2U2P9hYhgiMxRFvbVS4v0fiMcD" +
            "XMzk+WCxSTqYWs6mcbSu4OckVq8Mt0pn1z6JdjmcMhnq3LgHCHrjv3KgQd8aAcSfsqnLzMrw3XI3iNmI" +
            "4DPn52bP8vWbvMQgeHx7jY1NHqHmpPfH06waO0TB/uT8srkf0k4DahyZ30yAHUGrYxhPvV5i9bjAY+rz" +
            "v9Hd5bXml58nl8YnD/OltJ1nN5DoVBdcdro4xifNvFzDswcaMfhJQ174FQEpBpr2quF4EVAx93nf6WV6" +
            "9dNl+vT3gsckjfPy2kyxm833hm7uBo2M0NtJfl3XZyRh1hX4SkHXo7e6DTBkYUJFtz/UgoIEw4BdnnuV" +
            "VpVm8Hp3BHps4xKcO386il0Ki7oyYe4m838SxfdkNDHsQnLyf7hw16fpDIAuMbliy7iEGooBfnPneron" +
            "n04fvYC6TY6/r2y3yUYCBbLdTmFitdV/RT1PGstN9zxaAA/0q+2oYCAN+YeZ7vGbpMk6PnO6xiUN86sg" +
            "dzGX21ymbQ4EPXZ4QZMC40Jua/SropynjIl0cR5TYwopifVM2PksmwGt9UVfTsJiOSXQw9HnfzHO8buk" +
            "yqkfieXziIJ88cifzmfVx2lKz0EV9u0m/k7RjfhPpUrssNmZs34NO9Y2AcnCuaXVrV0VizRmJ4ThArDV" +
            "BEBJFsT1HAnAchee5uK6LkwjacRwTRjFhFK2nUzadoxz7PAyJk/1TI1HIey+d4vUrvXsS/teRKT4yeRs" +
            "LRkGzZV1eSWS2TSOtlOAohXJsKBat9drVqSDtVPEopXBdB6UUsdZEYUSsdWIzlcSMYbdhO0rhKAfHUTi" +
            "OQkSYaDWge/tWnN6DeEH93Bv/Il0eiGZsqP413xQRWbusZn/rxbF0pF17r82yZP3ZWBTwS5dP86ZdEM9" +
            "fjRzgvxw8QSmdvQp3WacKWfM3atezfXXqp2SD1UI6LPGS5KE62mbE6kw7+6azMtOtOnS5icGAbu3BGfV" +
            "9I6AWvODtQM+g4PBg0MIfGKAwOkw+lyHl2c2ELd+nWmtQqzcJQrtSy6RTFEZyFHJZ0ikPRPD9gEqtTss" +
            "PyGTSFAcKTEU+b336b7hvufdj2L99/E6++cBrmExlGNPr/pFKJVcyyGtTrlLoWNPyffxWC20MruuS8lI" +
            "Jh7Rcw76UEEfSznq9ge/7eF6KQiFPOm3dVrWO17hOGEe0Wj71ZpNmKyCMItJ+wKi/I/td1IQf9Nwp26C" +
            "f23rOGHuU5OC1UwMwdnt1hYsHprjj2GGOHZ5mZKhIbAyzC0u8cPo8M+cvUm80EFHkhzOcODLNiSMHGRs" +
            "dQkSxsLzK8y+cYaG0zOTEGA+ND/HgV/+CsTOnemuECIuveR3RT7+X1+VyNFoBrSBEa4NSipSrSHsenmc" +
            "NvrG2zvyOm8L3fRYWllhYWCAMIwqFAsPDwwwU8uQyabJpDyWCMQZxHGJgcbHE6ZlzLC0tMTg4xPFjtzE" +
            "5MYagiQOfTDpFOp2h2mhweX6Bcxcvc3FuiXKtyYnlRQbC7gPTCyxl4GxvHbM9+ilELzvwfGzPE+0m3/G" +
            "XlUus5rMcP3SAB++9i4PTk0TacOrMBZrNJvMLiywlCr98Lsuxw9O88v6THJ6eQgOnz11iZbVC029xd9r" +
            "h9X/zOPm/eaK3BjgOrR/+YdSv/hpHBgep+wH1RouGHxDHGkcpsmmPQi7DQD5DJp1BOYoIgx/GLJVWiMO" +
            "AVqMKCFOTkxw5dJDRkUFy6TSeq4iiCN8PMKKIlSLlOiyXSoStOoenxrn/njs5fvQwURRQq1TwXId0OkO" +
            "lXmdksEAum8KIEF1c4J7yMgNh0K3iLVLwfafPDvXQ531hLjwdw5u6yVcgd3u1zFPakEp55LIZCoUCsYF" +
            "CIU8+kyHjOSgBbbTd0lvIMzw8zOBgkSAI8DwHRwkTtSoPPvsU+Wee6q3yqRTNN7yBFx/+KSrLq/hzSzR" +
            "8nygMieKYOI5RSpHPZigW8kyODXNgaoJ8Pk+92eLy0gKnTp/lzPlLrJYrDBQKTCuHTCZN2nOJo5BqtcH" +
            "SSpnSSoVQWy5ULldYXF4liGJS6RSFXIZsJkWlFlBp+jSaLWJt0Domm/Y4dvgQzVbE6nKFO6rL5OKoW72" +
            "J78BT/YmNvxF93ZkawRPAr9Kl38m432RqcZ5Wy6dWb1KuNYhFaAUhIpD2XDKei6+NXd0olxih2Qqo1Wp" +
            "UKlXSc7O88dvf4raZ3qYtk0rhv/GNfPud7+I7M+dZKK1SabRotXw8ZXDErgBFhEI+x2BxgKMHp9EIohy" +
            "WVlb49nef48lnvsulhRKIw6HpaQ5MNWg0WziiqVVrXJpf4MXzlzh3aYF6KyCV8lAYWo0mhVyGMIpoNVu" +
            "srK4yV1rl1NlLXF5YolKrMZDNcN/dJzh6YIJKrcnKk3/LZNMqlbtUIrZCOzZ9R1/3xgPfwrLJrvaHFaK" +
            "Aey/MsGR+BK01cRQTJyurdDpFoZBjcHCAIDYU8nkymQzK9TAoK6hevsxDTzzGnT0Sj/Y8wje+idIjj7B" +
            "0/hLziyUuzi+xWrODn3bAVUIYRogIA4UCw/UmmXSW25ot4ljTbPpcnlvk1NkLzJfK5PMDDA+NECRqiTj" +
            "W+EHIaqXG7MIy5y7NUqk1yaQ8MikrF6U8L3EW08RRRLPZYLVcYW5hkdLKKuPDgxhzjOHBIqNDQ7ziwhk" +
            "Goq6nL4DlyI5N39Fvd45V4Bms9/81IyGl45jb5y6xGtgAeSbR4dhouh65Qp6hwSKRFoYGBsik0snS1+D" +
            "MzTH9qU8y9HxvEeBjx6H04EO4v/EbxF4KUbOoRP+U9jyiMEIpiI0hNpaotVHWPVU5GKMwxqC1fR5j3Wi" +
            "VUoiStYF1HBc3ZYXhTDpNJuUReCEZzyXlOImjWLKqS94SrXF0iGci0mJIKfCUQimFE0ccvXCWTBR1Szw" +
            "Bdi9Y+VoJe8FexAf6soEfpQsuZIBis8Ft334G84r7rMyhDTqO8TyXYnGAIDIYoxgZLOK5DlEQEq+UcH7" +
            "3dxn6+td6qmMswnPH7qDykz/FXcUiXhRRKOSZGBsl5aWpt1qslGu0goB6s4U2Lbv8djyUk0I5nt2j1XY" +
            "TVA7KTeG6Hq5j5bK2k5jjumSzOUZGRjg4VScKQ6rVOkopdBxTb7ZQIlbpaAxKhIznMpjPMDlcJJ/2KBY" +
            "H8BxFvdFAPfF1ipXVnRhyqwb+sqeO6gJ7ceDcFwV+ky4ISIBMGHDg6W9R+/mfo+UHNIOIlh/gOA6FfBa" +
            "7T0xRzGdRaMKL54k/8IeoL36xp3oa4Mmpwzzx4Gt5eTqD1pp8Lsv05AQpL0WsDa0g4vLCEhfnF7hweZ4" +
            "gjImCiCjWaN3h/tap2DMGe2hdDCZGazupu55HwfU45KbI5/JMT05QrVZptXxKKytcnlskNoYgDImiCNd" +
            "1GCwWmJ4aZ7BYIIwiRCxRzs0vMPQXXyLj7+hcuRWBL+2V5+Be5HsZeBo7jV17NWYMA7OzxN/4Bq03vYl" +
            "KvUWz5SMGcukUTrLDIpvxcJeXyH3iT5DHH+u5cn975ASfuf1lpFNpwkTHk8tmmBwfZWRokEwmRxhrTl+" +
            "4DK7DarVOtVq3UTCS/WsCyRGrVqmo1jZ42N0haEtA1gTh4HouxcIAE6NjHJ6aolqrslwuc/b8BSq1OpV" +
            "anTCMiKIYx3EoFgeQRPEoSmjUW9TrdfyvP8HQmRlU975MkYGnDcz23GHXQD/dOdZ+NfBpBa/HRqu/diX" +
            "8FsU/+xSXXvUqVstV/EQmKuTz5PMKcRzyzQaHPvZRct/6xoYDbneC5+56OV84fpIVhCkRRFmbkjGaMIp" +
            "otnxiDUGkabaahEGQnCqYnLO6+UjLjk0ViY2PDTtisXJdFEWY2BDHhnqjSa3RpN5s0QpC4o7oGsZYu5d" +
            "SLul0Gi/l4bkuruMRRxETf/klUsGOuM+CgU9fabnrH/pGQEMdvyv4bA3+eQjT3czVojXe6Rnyf/VVzt9" +
            "5klBrUqkU6UwW1/NINeoc/n8+xuCT37THHvSAZ06c5PPHTnIeQccxjuuQyaRwXKFWr3P+0mUuXJqj0Qp" +
            "ptEKWVlZZWV2lvFom9AOMNijlIKKuGA2DjRKsUWhxMMpFKXvIbhD6+DWf1XKV+cUVZhdLVKo1giim3qy" +
            "zWq6Q9lxSnovjKLTWhFFMtdbEcQPSqRQ6ipn89t+RPn0a1eXHY4AUnBuCz+2F/qeNvkdpBVB2s9vnDZy" +
            "ULiO2qlaTwU9+guhXfh0/kyWVSpNOZ8iHAQc+8mEK3/omEvbmkfnfxg7yx/kxStU6rqPIeC6O65BOp3E" +
            "ch1q9xoVLl/m7Z7/P7OKKnUabPo4YHKUII40oO8CqY4XVxtp+tGQPmBEH5diuDYOAaqXC2fMXeO7UWV4" +
            "4e4FytUEqlSaVcnFEmBwdIpXycF2HONbU6k0WllYIIqs+KOiYOz/4QZxW97YvgRUHPp+C5k1BQJ1rRAF" +
            "i+KDAT7KDs+HTly5x/Ktf5rtveyeO4zDgNzn4oQ+QeeLrPRPPV0Ym+b/Tg1yqNxgQIZfJ4ClJjKM2nF0" +
            "YaeqNJqWVFWYXFlmtNgn8kHzGI59Jo3FwUw5KBEeBo7B2LdZDyliLevs3szbdaa0Jw5Bavc5SqcTs/AI" +
            "rlQbZbI7iQJ5cOm1XX0rhKMuBmi2f0kqF+aVlavU6f/8bX8M5fXqL7T9XxRkfPrCw6Wa3vh/dom8EtHl" +
            "4BS4LfAHrttHViT1iDIf/5q85f/8rSOWyTH30T8l+7XHocdp68vBx/t/RA5QaPikRu7zGRsHQxmA0aKN" +
            "AnDXreTqdJhMYMGIt6CLJVmQAg6MMrjIJAYmNJGtU4sLR3r6c7IFPOkJE4TouqVSKTCZNJrBTtOO49qy" +
            "OZLOkKEEbQxhGVKp1zl+cJffsdzjy5OPJduauUQO+qGF2r88B3+sTC3/fwFuAV3abj9ts8PI//wyqUCD" +
            "/3W/3TDwXHngl3733QQpByB3lVbQB1/UIwwjiGB1rolgjoshmsowMDnLowBReJke1HtBo+jii0XFMrdE" +
            "ijDRxHGF0BGgbDU+5iVxkz6wXoxMCSiY0pUh5KfK5LGOjIxw5OE1ohFojIJVKoxwh8n1SnosSwU3y0jq" +
            "m2Woh58/zjmf+hvzOBGcMPGfgD3rquB1irzcWnlPwKQN3aevGek0IMH7qB7taNgRvezvVd/8jjiqP4Vq" +
            "daq2GMTFhGDE3t8DiYsl6FQrkMlkGCzmahw/hiEO1FdAINPVGiyDyWVlZ5eKlOUrLK0RRQBSHIIZ0yiW" +
            "fz5LPZUm5CjExWkdrKynHcchl0gwPFilk02QyGfKFAaamDxLG4HkejUaducuXiYMWac8ln81SyGXJ5jI" +
            "MEPHO5/+W2xs7C3IlUDHwaX0dTiuEPlvjt7n/MW0t9G/rNq/dEI95x4/R+pV/RspJMRVEjMVjtFo+Rkc" +
            "06nXiMKRcrhKEIZVanWq9zmA+Qz6T5cDEOBOiCLSi1mzRaDa4mEpRrtZZrVQIowA/CGk2W9TqDWr1Bs1" +
            "mkygK1ziO5SAG3w9otnyCIEQhiYXeY2BwBFF2yiyVloibdZaWAsLAp9FokM6k8atVbn/sK9x19sWd2Lv" +
            "affeEgo/togt3hD3f2mzgooIPaStMT+1lWRde8RDzb3kbzfkFGq0QjcKIIoqsErDZqFOpN/DDCD+KmDl" +
            "/Ec/zKOYzBM0GYRhiHI8IBz+MaPotKtU6QRhhEGIN9WbA3NIK3zt1huVqi5VyhdJKGeU4ZDNZHNej4Yd" +
            "cWlginUqxsLiIq0ApB18LQaRxXRfXEVZXlqlUKlRrdS5eniebfYGBTJril/+Cex57bGdnpFvMCXwI2+f" +
            "XBddlb7yCzyp4dQy/YXZ4dnw30CI8dfAo//XEXZjnfoAxhjDSSTQeB50IoHEUJZyjCRhOn7vA0soqGU9" +
            "hohCjNbE4xChiDdrENJs+lXqDWAPi0PQjZhdWaLRO8eK5y/hByPLyCsrxyOXyKOXQaPlcmF2gWqmRTTk" +
            "4SVi60Nh8XWX3I/utJuVylUarRb3ZpFau8OrzM9z+5DdIRTtedcYK/hj43PXctSb92hX6/c1a2k1QcJ+" +
            "G/xzD6/q5ozMW4YmxA3zo2F3UXNdOJWJLNGKt5O0gTmsu78ZqiDUGjcFB2836YtAoYlSiEU6s8O3VljY" +
            "YY7mZMXrNkd9JLOU2NO96aClMjEKjTGy11OJiEJTYsFPGaHRsiA2kdcwbS3P83PkXyYTBTqctFDwh8Cs" +
            "Gvnu1tCf7vAt4L0wZWyKG7xj4v4A7DYz1g4hCpfjrkSk+cPxlVJWLjiIwGqXalgRZN/KKtjsflEq0yUK" +
            "stb2MRonlCqYdqzlxK1FKQBzAwaytr4Q4Nhjse+LaVZRaW/Ib4rY9zKwfsYlYTiRAlAjxoMjFEa9fmuW" +
            "nLrxIqoct0wJLBv7dtYhnL3DdCCjB54B7BN6P3d7cMxqux7dGpvjQiZdTd613n3LcRIm3Hm7cmI3D0Y5" +
            "gJiK4SiVBjcyG+DtrKdeiw67vz5Ik8pndr9Y+PpOEMxkEZYlKKRvfGWfNViaoDiK0+Q6GPm9duMiPXzh" +
            "FqjcbXxP4DwY+28vLu8WemDK2gwHfhQ8AJ+vwcDdRXbeCAN8ZGuMPT7wc33ERo9fsUUISGjfZc5NEUqT" +
            "tsmVZk53OOg7A2VBJ1oY3eSJmA3GZNkmZNdJKps3O3GwdNsQ+SqzoRmzsxrGgxU+f+wGvX7iwY64D9sj" +
            "fHHwG+EAEQT9Fg27RNwI62GU6BRdq8L834U7ggV7Ly8URh5s1LuRyhMnxUEacDeYEoCO+YhLGO9EWW6x" +
            "v4lvjWB1l2GmwTUjr3EGSfMw6WaKNoGhroy0lS0dGbUUjQEbH3Fkr87Mzz3O8Vu5ZbSHw7SL8dgEu7qW" +
            "966p16JcQXbuGEL2hUKAJb7wMf+p2FyR7S7Qcly9OH+WLB45Q9dKEyvJBx1jZYy1iK3ZH6GY7uklC7dq" +
            "pqX2PNc6yTkBXok007d/bhKtku/40OLEmG0f82Ow5fuzSWbJx7/GeQpifhvdk4fGdjOBAn4XoG0JACqi" +
            "DXIZ3OfBx1YX/9HbQCJdyBf7s8Am+Pn4YLYIyeo2ATEe9Oh0IoU0aCffpIKD1p9KRaiNMx5POKbKdTja" +
            "ksylfszTPT1w8xW216iZetzMYG5n1p6bhs4W1ibE7vGQIqAbM2QO3fzKCj7aD/PYCg+A7DjOFQT4/fZw" +
            "nR3tman2HAe5dXeQdl89wsrxMNo57Jp72Wx78bBM+OQV+gS4DEiR4qREQObuH7Kd9+APpnYYAq1BsOi7" +
            "n8kW+Nn6Qb45NU3M9ZI0HbMVHroXtq7SZEDrLcIzmweUF3jh/gbury+SisOf4RJ2Yhl9ahT9dhfoBrJv" +
            "D/98JCAX5AH4itkTU7YmH28Ig1F2X5XSW7w2O8tToFM8NjtpTc/YYx2plXl2a496VRcZbDQpR0BfC0Uj" +
            "oCL902JhPL0F9FRuh60YT0I0K87sZdeATQM3A78oubWaCoRCFFKKQyWadh0pzLGZyzBQGeaE4wosDw5T" +
            "SXR/telUMhAHHamVOVpa5o7rCRLPBQBSQ27kpYlvUHbe2ks782m2N2icM9BZSf4+wXzgQARCDysAbmkr" +
            "9B9H63n7zC1851LwUNS/FYjrLbDbPQibHUjrLaipDxUvRdFwipewOWQPKGFxjV0+FMKAYBoz7DSZaTaa" +
            "adcb8BgNhSDH011ZVO7WgbwcDXM4Xm18bP/hv/254/F//m2ceDw8AJewOzv3AgfYbAZEHIngghn8Zw3v" +
            "7Urnt4WPHooLlgg0H/NhWJcTSgWeDuJACsgZyYsPKDdJlfMJe4cDHHPg3wN+1sBXYbwS0X6awNSRf7zM" +
            "KfkvDiwZ+jR2cxbpDpLF6qLVlW8SV3KNTXX6dtL1LwH9U8CGBc9fTur5T7DsC6sA54P8w8JxYInrD9Sj" +
            "0RpgDNpX/mIb/JNa2tdcuzbvGfiYgsB34ceCUgn+i4WG6t5rcNEi47iWxbf0INkDFTYH9TkBtPCPwXYE" +
            "nDfwM8Ea63OlxE6AG/DeBP1bwCb0H51nsJW4WAgLbsX8M/JXA+wy8C7ifPRZk9xB1A99W1sXlg0DvIWV" +
            "vIG4mAmpjDngU+CTw81hn/dvpcgfsPsAqNtzuFw182MDpG1yfXeFmJKA2XgT+N+APDPysAz+mbUSQKfZ" +
            "fuyJgzrErqi/E8FGB8ze6Uv3AfuvoHcPAeQW/nYZ/14J3Gng38GqsnqbILiz9u0SA1S+VgW8Cn8nCn7f" +
            "sidUvGdz0BNSGgQZ2FfNxbKjhtwA/AjwEjBpIJ3a2vp8bmiA04ItdOZaAp4C/wkYHu5DU8SWHlwwBbcJ" +
            "54I+APzKWC73KgdcZeMjASWDMWEJSkpyeyLq70FYuPe2fa+6JxmqrtViN9aKC7wNPRfDXwLfUHhyttB/" +
            "hIvIw9qsF+B2x4ek2wFgn+EeTP98j1vC5AdttwC3Am4EvJ3++pQZf2WWdr8DJjWUAfOI5eE/yewX4yt2" +
            "2/g/G2LllCX67Cc0YjgocNjBk7LSXxxJX++OKsERSFyiLFYIvOHAuhNMhvJCCMwqW2yaFl9v6PAw8/Rz" +
            "8fr/b24n8xrZ/pWo57xoGNo7dCRGZ6XzelSlLZK09GHNlewwsJ27oW0bqNjZwpknSDV+7xA3vvtmwFuD" +
            "izTt5t8cyjNkUkd3A8Kbne1mX4x1lPLIXZWwqb3PbH970/P0dz45f8b4xV782tWfz87aZp81RHjTw4KY" +
            "KDLPe2Z+QHR5aJvAVYe3wmr5zn20wvKkj94RY9ike3elHvhu0CahzYDd3dudAbCAAAw8beKqDQp/a/NV" +
            "djQMlX8dyx/Mvb8UZjO2Uzq/s/Vdp09PJz84P4cFNz65At2VcLV1S9069zu9t/vKvVY6BRzZ88TvnZsf" +
            "pMq2BhxF5ym4lEZP8vv6unbo2tCdJdwUn23YaM/DxbaaF92/qiM7r0Y50WxJQR75bXQ92pHtqmzQf36a" +
            "M9gA9tUUej25Tl2uW0U26LaaTDVNHl215ZJs0G6ama7S9s8wtp7BrjV8yfW3bnvYU1lmR3+tIMJzc65Q" +
            "dtiOKzsZ3EsWbtyOgTffen9x7sOPel7doZPvdh6+RX+fz4U1t2OrdbsvoNt2WMtAO3u8koC935LnltLS" +
            "p7Y90jONWfXh8i3c+3iHvbBi/nchAsHF6ajf8zds8b99fAX65fVPsyqct5V+Nja69L/A7ybtPY2Wx3+z" +
            "Is/3VfaItPyUrwK9syqcTK6xPVW/uqMfTbC2/dVtGL3XppZxO/H6SbmYHsufvtPMz23Atthk/jOl2/Na" +
            "wpgcS+ISxGbaF5t9hvQIzmwTgNZlii4Y9jaX0K+fJLd7vvCnrS+822l/dw4Yt9XAPbnEPbF0fTK7jHfe" +
            "2Qrdl9FqXnZbTiW1ltu0gMGMs4T2CnTWuULnQ2f/G9DJ+a9i8N71d2JsTdvfmTff7jd2uFrZrZLvjH2G" +
            "9DTsejGuU0Wu6vXq/E7+J/bC7Fqh7xWYC6vxKH2V9gDcT0NpKZ4u5uZsBaz/b0GnGCoG/ZzayWLBsX7a" +
            "4TmyTf7sdwx1t2I4DdVtGr3XZaTm7RjIrtKeyrT7S9ZWqSC/jt4atCKjd0M7pa3NmnQP0e+2biUC9HdF" +
            "t+b5JhHOz/rU8wrpg3s7j4Q4hs1PY3nKpLRvlINh6qm2j2zK6TddZTufg9NSWXeD32b7NW44fIluN33b" +
            "t2RrmyuV1t/qQLd/ZJPF3u4xvr8yGDZzeJs1TZn21uNVKr7N+j14lXbdldJUuSbu86fmDOyincxV2zWl" +
            "tU5s26+A2L9Wvpo/a0P+btNFXtsdsWsZ3ZPzw5sRXqfxWisTNqvSdKBK3en94i8Zu0LZuQxid7Xj4anX" +
            "ppowdpnt4U7uOd/t+PwkoeX56u/y2G78tzBlXtKf97EZvQriFG4zd7gu8XtFgb+ElilsEdAu7wi0CuoV" +
            "d4RYB3cKucIuAbmFXuEVAt7Ar3CKgW9gVbhHQLewK+5aAzEYHt62uj19NS36jYNY3IHz52qlvfuxbAuo" +
            "CD2NV7/10g7iFHeJmJqA29nzrzE4g8JbEPeMt10598+NmIKCZzb4zWN+ZtutlpwP+ltOH2eQnvDltYiz" +
            "sNDpu3inRU9pe3k/Sd6ZZTv5ut2FfRfN4qW5t3gnezJX+yI8a66+9eRfmTtL2VFbiOdC5G2Q4+XuGfYi" +
            "bgQN17gowBgz2K7yWr/NO8JsJZ3uo4952TvI7SdvL+22ONAM8lKT9TfaprHczENDV8BVZd93sFU9v2hn" +
            "S6a23m7Q7LivxC2pPyb/f9gRN3rleu3p3hJuVgGawQR76Iaiu7FHaXt7vVEtsdiPudVPAnuJmIKCZDuG" +
            "57ae7090G+5L9vxRwMxDQGpJ9Y51bjx69WvoOXLdgA7tEJ5fZrCTdd0pTuMkICK7Y/fr+Tdro9hSxFmU" +
            "kWSbvy87fjE27SR7Z1IZ9GWHkpiOgBL/c8XvnkrdTKH0qWbE9yu5ll+uJ9qLgOBvbcEsG6heSbdZrHd1" +
            "WxiW6lE7imkn+3qudtX1Hsl++k8vOYBcL+5KAbuEmQYcmessocj3nu3kLzw6vm5IDvZSxyYTR3k/2IOv" +
            "75falPugW9gm22Hi4+errgmC3HOgW9iHMlTt22/5PfV+J7ZaA/j8ewe5SoDIpQAAAAABJRU5ErkJggg=" +
            "=")]
        public string VMNotRunning {
            get {
                return ((string)(this["VMNotRunning"]));
            }
        }
    }
}
